import type { Language, TranslationData } from "../types/language.types";

export const COMMON_INFO = {
  name: "Daniel NIYOMUGENGA",
  email: "danielhustler.hacker@gmail.com",
  phone: "+250 791832842",
  address: "KN 183 ST, KN 222 ST, Kigali, Rwanda",
  nationality: "Rwandan",
  dob: "June 16",
  gender: "Male",
  profileImage: {
    src: "/images/profile.jpg",
    alt: "Portrait of Daniel Niyomugenga",
    width: 640,
    height: 960,
  },
  socials: [
    { name: "LinkedIn", url: "https://www.linkedin.com/in/daniel-niyomugenga/" },
    { name: "GitHub", url: "https://github.com/danielstriver" },
    { name: "Instagram", url: "https://www.instagram.com/danielthepentester/" },
  ],
};

export const DATA: Record<Language, TranslationData> = {
  en: {
    title: "Software Engineer & Robotics Enthusiast",
    about: "A motivated and self-driven technologist with a strong background in Computer Science, Cybersecurity, and Robotics. Proven leader in student-led tech initiatives and an active researcher in the robotics field. Dedicated to building innovative solutions and fostering collaborative environments for technical growth.",
    experience: [
      {
        title: "Robotics Team Leader (CUE Robot Research)",
        company: "TechRise Rwanda",
        location: "Kigali, Rwanda",
        period: "Nov 2024 – Feb 2025",
        description: [
          "Led a research team studying the CUE robot.",
          "Explored history, functionality, and programming.",
          "Conducted testing using pre-coded challenges.",
          "Presented findings and insights to stakeholders.",
        ],
      },
      {
        title: "President of the Computer Department Science Club",
        company: "New Life Christian High School",
        location: "Kigali, Rwanda",
        period: "2023 – 2024",
        description: [
          "Led a team in developing simple web-based projects.",
          "Designed and implemented basic front-end and back-end web solutions.",
          "Organized and facilitated coding sessions for fellow students.",
          "Provided technical guidance on HTML, CSS, and JavaScript fundamentals.",
          "Managed project timelines and ensured team collaboration.",
        ],
      },
      {
        title: "Robotics & Programming Trainee",
        company: "African Institute for Mathematical Sciences (AIMS)",
        location: "Kigali, Rwanda",
        period: "2022 – 2023",
        description: [
          "Hands-on robotics programming working with sensors, motors, and microcontrollers.",
          "Applied programming skills to robotics challenges.",
          "Collaborated on real-world robotics applications.",
        ],
      },
      {
        title: "Cybersecurity Fundamentals Trainee",
        company: "ISC2",
        location: "Kigali, Rwanda",
        period: "Aug 2022 – Sep 2022",
        description: [
          "Completed the Certified in Cybersecurity (CC) course.",
          "Gained foundational knowledge in network security and threat analysis.",
          "Learned incident response and security best practices.",
        ],
      },
    ],
    education: [
      {
        degree: "Advanced General Certificate of Secondary Education",
        institution: "New Life Christian High School",
        period: "2021 – 2024",
        website: "https://nlca.ac.rw/",
      },
      {
        degree: "Web Development Course",
        institution: "W3Schools",
        period: "Jan 2020 – Jun 2020",
        website: "https://www.w3schools.com/",
      },
    ],
    projects: [
      {
        title: "RWANDA TOURIST ASSISTANT",
        description: "An AI-powered travel companion designed to help tourists explore Rwanda's rich culture, attractions, and heritage with ease.",
        image: "/images/rwanda-tour-image.jpg",
        link: "https://rwanda-tour-ai.vercel.app",
        tags: ["React", "AI", "Vercel", "Tailwind"],
      },
      {
        title: "Project 2",
        description: "Innovation in progress. A new project is currently under development to solve real-world challenges.",
        image: "/images/guide-fix-image.png",
        status: "Coming Soon",
      },
      {
        title: "Project 3",
        description: "Exploring new horizons. Stay tuned for an upcoming robotics-focused project.",
        image: "/images/logo.png",
        status: "Coming Soon",
      },
    ],
    gallery: [
      { src: "/images/Gallery/daniel 1.jpg", alt: "Daniel at a Tech Event", caption: "Leading Tech Initiatives" },
      { src: "/images/Gallery/20220524_155239.jpg", alt: "Daniel with Robot", caption: "Robotics Research Days" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.00.jpeg", alt: "Daniel in the Lab", caption: "Innovation in Progress" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.01.jpeg", alt: "Daniel Presentation", caption: "Sharing Knowledge" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.02.jpeg", alt: "Daniel Programming", caption: "Coding the Future" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.03.jpeg", alt: "Daniel Group Photo", caption: "Team Collaboration" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.04.jpeg", alt: "Daniel with Mentors", caption: "Learning from the Best" },
      { src: "/images/Gallery/20220524_103421.jpg", alt: "Early Robotics Days", caption: "Where it all Started" },
      { src: "/images/Gallery/20220524_103426.jpg", alt: "Robotics Workshop", caption: "Hands-on Learning" },
      { src: "/images/Gallery/20220524_103426 - Copy.jpg", alt: "Robotics Workshop Session", caption: "Deep Dive into Robotics" },
      { src: "/images/Gallery/20220524_103447 - Copy.jpg", alt: "Robotics Testing", caption: "Rigorous Testing Phase" },
      { src: "/images/Gallery/20220524_155233 - Copy.jpg", alt: "Robotics Team", caption: "United for Innovation" },
      { src: "/images/Gallery/20220524_155235.jpg", alt: "Robotics Lab", caption: "Where Ideas Come to Life" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.01 (1).jpeg", alt: "Tech Conference", caption: "Networking with Peers" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.02 (1).jpeg", alt: "Hackathon", caption: "Building Fast" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.03 (1).jpeg", alt: "Lab Work", caption: "Precision in Engineering" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.03 (2).jpeg", alt: "Project Showcase", caption: "Displaying Results" },
    ],    certifications: [
      "Certified in Cybersecurity — ISC2 (2022)",
      "IOC Learning Sprint Certificate — IOC Young Leaders (2024)",
      "iLead Leadership Certificate — Maxwell Leadership Foundation (2024)",
      "Robotics Experiential Learning Certificate — AIMS (2022–2023)",
      "Science Club Certificate — New Life Christian High School (2023–2024)",
    ],
    skills: [
      { category: "Web Development", items: ["HTML", "CSS", "JavaScript", "Front-end Development", "Back-end Solutions"] },
      { category: "Robotics", items: ["Programming", "Sensors", "Motors", "Microcontrollers", "Research"] },
      { category: "Security", items: ["Cybersecurity Fundamentals", "Network Security", "Threat Analysis", "Incident Response"] },
      { category: "Digital Tools", items: ["Microsoft Word", "Excel", "PowerPoint", "Outlook", "Zoom", "Skype"] },
      { category: "Soft Skills", items: ["Leadership", "Organizational Planning", "Teamwork", "Communication", "Self-driven"] },
      { category: "Languages", items: ["Kinyarwanda (Mother Tongue)", "English (C1 Proficient)"] },
    ],
    nav: {
      experience: "Experience",
      projects: "Projects",
      gallery: "Gallery",
      skills: "Skills",
      education: "Education",
      contact: "Contact",
      hireMe: "Hire Me",
    },
    sections: {
      experience: "Professional Experience",
      projects: "Featured Projects",
      gallery: "Moments & Memories",
      skills: "Skills & Expertise",
      education: "Education & Certifications",
      contact: "Get in Touch",
      about: "About Me",
      academic: "Academic Path",
      certifications: "Certifications",
    },
    contact: {
      title: "Get in Touch",
      subtitle: "Let's connect",
      description: "Whether you want to collaborate, discuss an opportunity, or ask a technical question, this form will send your message directly to my inbox.",
      name: "Your Name",
      email: "Email Address",
      phone: "Phone",
      address: "Address",
      subject: "Subject",
      message: "Message",
      send: "Send Message",
      sending: "Sending message...",
      success: "Message sent successfully!",
      error: "Something went wrong. Please try again.",
      namePlaceholder: "John Doe",
      emailPlaceholder: "john@example.com",
      messagePlaceholder: "Share a few details about your project, role, or question.",
    },
    footer: {
      rights: "All rights reserved.",
      visits: "Website Visits",
    },
    ui: {
      welcome: "Welcome to my portfolio",
      getInTouch: "Get in touch",
      viewWork: "View Work",
      scrollDown: "Scroll Down",
      nationality: "Nationality",
      born: "Born",
      curiosity: "Curiosity",
      innovation: "Innovation",
      drivenBy: "Driven by",
      focusedOn: "Focused on",
    }
  },
  rw: {
    title: "Enjenyeri mu by'Inganda n'Ubuhanga mu by'Imashini",
    about: "Umukozi ushishikajwe kandi wiyobora mu by'ikoranabuhanga ufite ubumenyi bukomeye muri Siyansi ya Mudasobwa, Cybersecurity, n'Imashini zikora. Umuyobozi ugaragaza ubuhanga mu nzego z'abanyeshuri mu ikoranabuhanga kandi akaba n'umushakashatsi mu by'imashini zikora. Twiyemeje kubaka ibisubizo bishya no guteza imbere ubufatanye mu gukura mu bya tekiniki.",
    experience: [
      {
        title: "Umuyobozi w'Ikipe ya Robotics (Ubushakashatsi kuri CUE Robot)",
        company: "TechRise Rwanda",
        location: "Kigali, Rwanda",
        period: "Ugushyingo 2024 – Gashyantare 2025",
        description: [
          "Nayoboye ikipe y'ubushakashatsi yigaga kuri robot ya CUE.",
          "Nasesenguye amateka, imikorere, n'uburyo bwo kuyiporogaramu.",
          "Nakoze isuzuma nifashishije imbogamizi zabonetse mbere.",
          "Nerekanye ibyavuye mu bushakashatsi n'inyandiko ku bafatanyabikorwa.",
        ],
      },
      {
        title: "Perezida wa Club ya Siyansi ya Mudasobwa",
        company: "New Life Christian High School",
        location: "Kigali, Rwanda",
        period: "2023 – 2024",
        description: [
          "Nayoboye ikipe mu gukora imishinga yoroheje yo kuri murandasi.",
          "Nakoze kandi nshyira mu bikorwa uburyo bw'imbere n'inyuma bw'imbuga za murandasi.",
          "Nateguye kandi nayoboye amasomo yo gukora porogaramu ku bandi banyeshuri.",
          "Natanze ubujyanama mu bya tekiniki kuri HTML, CSS, na JavaScript.",
          "Nacunze igihe cy'imishinga kandi nemeza ubufatanye mu ikipe.",
        ],
      },
      {
        title: "Inararibonye mu by'Imashini na Porogaramu",
        company: "African Institute for Mathematical Sciences (AIMS)",
        location: "Kigali, Rwanda",
        period: "2022 – 2023",
        description: [
          "Nakoze imyitozo ngiro mu guporogaramu imashini nifashishije utwumvirizo, moteri, na mikoro-ntumwa.",
          "Nashyize mu bikorwa ubumenyi bwo guporogaramu mu mbogamizi z'imashini zikora.",
          "Nafatanyije n'abandi mu gukora imashini zikoreshwa mu buzima busanzwe.",
        ],
      },
      {
        title: "Amahugurwa y'Ibanze muri Cybersecurity",
        company: "ISC2",
        location: "Kigali, Rwanda",
        period: "Kanama 2022 – Nzeri 2022",
        description: [
          "Narangiye amasomo ya Certified in Cybersecurity (CC).",
          "Nabonye ubumenyi bw'ibanze mu mutekano w'urusobe n'isesengura ry'ibishobora guhungabanya umutekano.",
          "Nize uburyo bwo gutabara igihe habaye ikibazo n'uburyo bwiza bwo kurinda umutekano.",
        ],
      },
    ],
    education: [
      {
        degree: "Impamyabumenyi y'Amashuri Yisumbuye mu masomo rusange",
        institution: "New Life Christian High School",
        period: "2021 – 2024",
        website: "https://nlca.ac.rw/",
      },
      {
        degree: "Amahugurwa yo kubaka imbuga za murandasi",
        institution: "W3Schools",
        period: "Mutarama 2020 – Kamena 2020",
        website: "https://www.w3schools.com/",
      },
    ],
    projects: [
      {
        title: "RWANDA TOURIST ASSISTANT",
        description: "Ubufasha bugufasha abakerarugendo gusura u Rwanda, kumenya imigenzo, ahantu nyaburanga n'amateka yarwo mu buryo bworoshye.",
        image: "/images/rwanda-tour-image.jpg",
        link: "https://rwanda-tour-ai.vercel.app",
        tags: ["React", "AI", "Vercel", "Tailwind"],
      },
      {
        title: "Umushinga wa 2",
        description: "Guhanga udushya birakomeje. Umushinga mushya uri gukorwa kugira ngo ukemure imbogamizi z'ubuzima busanzwe.",
        image: "/images/guide-fix-image.png",
        status: "Uzaza vuba",
      },
      {
        title: "Umushinga wa 3",
        description: "Gushakashatsha ibishya. Tegereza umushinga ugiye kuza wibanze kuri robotics.",
        image: "/images/logo.png",
        status: "Uzaza vuba",
      },
    ],
    gallery: [
      { src: "/images/Gallery/daniel 1.jpg", alt: "Daniel mu gikorwa cya tekiniki", caption: "Kuyobora Ibikorwa by'Ikoranabuhanga" },
      { src: "/images/Gallery/20220524_155239.jpg", alt: "Daniel ari kumwe na Robot", caption: "Iminsi y'Ubushakashatsi kuri Robotics" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.00.jpeg", alt: "Daniel muri laboratwari", caption: "Guhanga Udushya Turakomeje" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.01.jpeg", alt: "Daniel atanga ikiganiro", caption: "Gusangira Ubumenyi" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.02.jpeg", alt: "Daniel akora porogaramu", caption: "Kubaka Ejo Hazaza" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.03.jpeg", alt: "Ifoto y'ikipe", caption: "Gukorera hamwe mu Ikipe" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.04.jpeg", alt: "Daniel n'abamufasha", caption: "Kwigira ku Bazobereye" },
      { src: "/images/Gallery/20220524_103421.jpg", alt: "Iminsi ya mbere ya robotics", caption: "Aho Byatangiye Hose" },
      { src: "/images/Gallery/20220524_103426.jpg", alt: "Amahugurwa kuri Robotics", caption: "Kwiga mu Bikorwa" },
      { src: "/images/Gallery/20220524_103426 - Copy.jpg", alt: "Kwiga Imikorere ya Robot", caption: "Gusesengura Ikoranabuhanga" },
      { src: "/images/Gallery/20220524_103447 - Copy.jpg", alt: "Isuzuma rya Robot", caption: "Isuzuma ry'Imikorere" },
      { src: "/images/Gallery/20220524_155233 - Copy.jpg", alt: "Ikipe ya Robotics", caption: "Ubufatanye mu Guhanga Udushya" },
      { src: "/images/Gallery/20220524_155235.jpg", alt: "Laboratwari ya Robotics", caption: "Aho Udushya Tuvukira" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.01 (1).jpeg", alt: "Inama ku Ikoranabuhanga", caption: "Gusabana n'Abandi mu Mwuga" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.02 (1).jpeg", alt: "Amarushanwa yo Gukora Porogaramu", caption: "Kubaka mu Buryo bwihuse" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.03 (1).jpeg", alt: "Akazi muri Laboratwari", caption: "Ubuhanga mu Kwubaka" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.03 (2).jpeg", alt: "Kugaragaza Ibyakozwe", caption: "Kwerekana Ibyavuye mu Mushinga" },
    ],
    certifications: [
      "Impamyabumenyi muri Cybersecurity — ISC2 (2022)",
      "Icyemezo cya IOC Learning Sprint — IOC Young Leaders (2024)",
      "Icyemezo cy'Ubuhanga mu Buyobozi — Maxwell Leadership Foundation (2024)",
      "Icyemezo cy'imyitozo ngiro mu by'imashini zikora — AIMS (2022–2023)",
      "Icyemezo cya Club ya Siyansi — New Life Christian High School (2023–2024)",
    ],
    skills: [
      { category: "Iterambere ry'Imbuga", items: ["HTML", "CSS", "JavaScript", "Iterambere ry'imbere", "Ibisubizo by'inyuma"] },
      { category: "Imashini zikora", items: ["Guporogaramu", "Utwumvirizo", "Moteri", "Mikoro-ntumwa", "Ubushakashatsi"] },
      { category: "Umutekano", items: ["Ibanze rya Cybersecurity", "Umutekano w'Urusobe", "Isesengura ry'Ibyago", "Gutabara"] },
      { category: "Ibikoresho by'Ikoranabuhanga", items: ["Microsoft Word", "Excel", "PowerPoint", "Outlook", "Zoom", "Skype"] },
      { category: "Ubumenyi mu mibanire", items: ["Ubuhanga mu Buyobozi", "Gutegura", "Gukorera hamwe", "Itumanaho", "Kwiyobora"] },
      { category: "Indimi", items: ["Ikinyarwanda (Ururimi kavukire)", "Icyongereza (C1 Proficient)"] },
    ],
    nav: {
      experience: "Inararibonye",
      projects: "Imishinga",
      gallery: "Igalari",
      skills: "Ubumenyi",
      education: "Amashuri",
      contact: "Twandikire",
      hireMe: "Mpe Akazi",
    },
    sections: {
      experience: "Inararibonye mu Kazi",
      projects: "Imishinga Y'ingenzi",
      gallery: "Ibihe n'Inzibutso",
      skills: "Ubumenyi n'Ubuhanga",
      education: "Amashuri n'Impamyabumenyi",
      contact: "Tuvugane",
      about: "Njyewe mwayo",
      academic: "Amashuri Nize",
      certifications: "Impamyabumenyi",
    },
    contact: {
      title: "Tuvugane",
      subtitle: "Twandikire",
      description: "Naba wifuza ubufatanye, kuganira ku kintu runaka, cyangwa ufite ikibazo cya tekiniki, koresha iyi fomu ubutumwa bwawe buhite bungeraho.",
      name: "Izina ryawe",
      email: "Imeri yawe",
      phone: "Telefoni",
      address: "Aho uherereye",
      subject: "Icyo uvugaho",
      message: "Ubutumwa",
      send: "Ohereza Ubutumwa",
      sending: "Ubutumwa buracyoherezwa...",
      success: "Ubutumwa bwoherejwe neza!",
      error: "Hagize ikibazo kiba. Ongera ugerageze.",
      namePlaceholder: "Izina ryawe hano",
      emailPlaceholder: "imeri@urubuga.rw",
      messagePlaceholder: "Andika ubutumwa bwawe hano...",
    },
    footer: {
      rights: "Uburenganzira bwose burasigasigwa.",
      visits: "Abasuye Urubuga",
    },
    ui: {
      welcome: "Murakaza neza ku rubuga rwanjye",
      getInTouch: "Tuvugane",
      viewWork: "Reba Ibyo Nakoze",
      scrollDown: "Manuka Hasi",
      nationality: "Ubwenegihugu",
      born: "Yavutse",
      curiosity: "Amatsiko",
      innovation: "Iguhoraho",
      drivenBy: "Biyobowe n'",
      focusedOn: "Bishingiye ku",
    }
  },
  fr: {
    title: "Ingénieur Logiciel & Passionné de Robotique",
    about: "Un technologue motivé et autodidacte doté d'une solide formation en informatique, en cybersécurité et en robotique. Leader reconnu dans les initiatives technologiques dirigées par des étudiants et chercheur actif dans le domaine de la robotique. Dédié à la création de solutions innovantes et à la promotion d'environnements collaboratifs pour la croissance technique.",
    experience: [
      {
        title: "Chef d'équipe Robotique (Recherche Robot CUE)",
        company: "TechRise Rwanda",
        location: "Kigali, Rwanda",
        period: "Nov 2024 – Fév 2025",
        description: [
          "Direction d'une équipe de recherche étudiant le robot CUE.",
          "Exploration de l'histoire, de la fonctionnalité et de la programmation.",
          "Réalisation de tests à l'aide de défis pré-codés.",
          "Présentation des résultats et des perspectives aux parties prenantes.",
        ],
      },
      {
        title: "Président du club scientifique du département informatique",
        company: "New Life Christian High School",
        location: "Kigali, Rwanda",
        period: "2023 – 2024",
        description: [
          "Direction d'une équipe dans le développement de projets web simples.",
          "Conception et mise en œuvre de solutions web front-end et back-end de base.",
          "Organisation et animation de sessions de codage pour les étudiants.",
          "Conseils techniques sur les bases du HTML, CSS et JavaScript.",
          "Gestion des délais de projet et garantie de la collaboration d'équipe.",
        ],
      },
      {
        title: "Stagiaire en Robotique et Programmation",
        company: "African Institute for Mathematical Sciences (AIMS)",
        location: "Kigali, Rwanda",
        period: "2022 – 2023",
        description: [
          "Programmation robotique pratique avec capteurs, moteurs et microcontrôleurs.",
          "Application des compétences en programmation aux défis de la robotique.",
          "Collaboration sur des applications robotiques réelles.",
        ],
      },
      {
        title: "Stagiaire en Fondamentaux de la Cybersécurité",
        company: "ISC2",
        location: "Kigali, Rwanda",
        period: "Août 2022 – Sept 2022",
        description: [
          "Cours Certified in Cybersecurity (CC) terminé.",
          "Connaissances de base en sécurité réseau et analyse des menaces.",
          "Apprentissage de la réponse aux incidents et des meilleures pratiques de sécurité.",
        ],
      },
    ],
    education: [
      {
        degree: "Certificat Général Avancé d'Enseignement Secondaire",
        institution: "New Life Christian High School",
        period: "2021 – 2024",
        website: "https://nlca.ac.rw/",
      },
      {
        degree: "Cours de Développement Web",
        institution: "W3Schools",
        period: "Jan 2020 – Juin 2020",
        website: "https://www.w3schools.com/",
      },
    ],
    projects: [
      {
        title: "RWANDA TOURIST ASSISTANT",
        description: "Un compagnon de voyage alimenté par l'IA conçu pour aider les touristes à explorer la riche culture, les attractions et le patrimoine du Rwanda en toute facilité.",
        image: "/images/rwanda-tour-image.jpg",
        link: "https://rwanda-tour-ai.vercel.app",
        tags: ["React", "AI", "Vercel", "Tailwind"],
      },
      {
        title: "Projet 2",
        description: "Innovation en cours. Un nouveau projet est actuellement en développement pour résoudre des défis du monde réel.",
        image: "/images/guide-fix-image.png",
        status: "Prochainement",
      },
      {
        title: "Projet 3",
        description: "Explorer de nouveaux horizons. Restez à l'écoute pour un prochain projet axé sur la robotique.",
        image: "/images/logo.png",
        status: "Prochainement",
      },
    ],
    gallery: [
      { src: "/images/Gallery/daniel 1.jpg", alt: "Daniel lors d'un événement technologique", caption: "Direction d'initiatives technologiques" },
      { src: "/images/Gallery/20220524_155239.jpg", alt: "Daniel avec un robot", caption: "Journées de recherche en robotique" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.00.jpeg", alt: "Daniel dans le laboratoire", caption: "Innovation en cours" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.01.jpeg", alt: "Présentation de Daniel", caption: "Partage de connaissances" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.02.jpeg", alt: "Daniel en train de programmer", caption: "Coder l'avenir" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.03.jpeg", alt: "Photo d'équipe", caption: "Collaboration d'équipe" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.04.jpeg", alt: "Daniel avec des mentors", caption: "Apprendre des meilleurs" },
      { src: "/images/Gallery/20220524_103421.jpg", alt: "Premiers jours en robotique", caption: "Là où tout a commencé" },
      { src: "/images/Gallery/20220524_103426.jpg", alt: "Atelier de Robotique", caption: "Apprentissage Pratique" },
      { src: "/images/Gallery/20220524_103426 - Copy.jpg", alt: "Session de Formation Robotique", caption: "Exploration Technologique" },
      { src: "/images/Gallery/20220524_103447 - Copy.jpg", alt: "Phase de Tests Robotiques", caption: "Validation de Projet" },
      { src: "/images/Gallery/20220524_155233 - Copy.jpg", alt: "Équipe de Robotique", caption: "Unis pour l'Innovation" },
      { src: "/images/Gallery/20220524_155235.jpg", alt: "Laboratoire de Robotique", caption: "Le Berceau des Idées" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.01 (1).jpeg", alt: "Conférence Technologique", caption: "Échange avec des Pairs" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.02 (1).jpeg", alt: "Hackathon", caption: "Développement Agile" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.03 (1).jpeg", alt: "Travail en Laboratoire", caption: "Rigueur et Précision" },
      { src: "/images/Gallery/WhatsApp Image 2026-04-15 at 05.54.03 (2).jpeg", alt: "Présentation de Projet", caption: "Démonstration de Résultats" },
    ],
    certifications: [
      "Certifié en Cybersécurité — ISC2 (2022)",
      "Certificat d'apprentissage IOC — Jeunes leaders du CIO (2024)",
      "Certificat de Leadership iLead — Fondation Maxwell Leadership (2024)",
      "Certificat d'apprentissage expérientiel en robotique — AIMS (2022–2023)",
      "Certificat du club scientifique — New Life Christian High School (2023–2024)",
    ],
    skills: [
      { category: "Développement Web", items: ["HTML", "CSS", "JavaScript", "Développement Front-end", "Solutions Back-end"] },
      { category: "Robotique", items: ["Programmation", "Capteurs", "Moteurs", "Microcontrôleurs", "Recherche"] },
      { category: "Sécurité", items: ["Bases de la Cybersécurité", "Sécurité Réseau", "Analyse des Menaces", "Réponse aux Incidents"] },
      { category: "Outils Numériques", items: ["Microsoft Word", "Excel", "PowerPoint", "Outlook", "Zoom", "Skype"] },
      { category: "Compétences Douces", items: ["Leadership", "Organisation", "Travail d'Équipe", "Communication", "Autonomie"] },
      { category: "Langues", items: ["Kinyarwanda (Langue maternelle)", "Anglais (C1 Proficient)"] },
    ],
    nav: {
      experience: "Expérience",
      projects: "Projets",
      gallery: "Galerie",
      skills: "Compétences",
      education: "Éducation",
      contact: "Contact",
      hireMe: "Recrutez-moi",
    },
    sections: {
      experience: "Expérience Professionnelle",
      projects: "Projets Phares",
      gallery: "Moments & Souvenirs",
      skills: "Compétences & Expertise",
      education: "Éducation & Certifications",
      contact: "Contactez-moi",
      about: "À Propos",
      academic: "Parcours Académique",
      certifications: "Certifications",
    },
    contact: {
      title: "Contactez-moi",
      subtitle: "Parlons-en",
      description: "Que vous souhaitiez collaborer, discuter d'une opportunité ou poser une question technique, ce formulaire enverra votre message directement dans ma boîte de réception.",
      name: "Votre Nom",
      email: "Adresse Email",
      phone: "Téléphone",
      address: "Adresse",
      subject: "Sujet",
      message: "Message",
      send: "Envoyer le Message",
      sending: "Envoi du message...",
      success: "Message envoyé avec succès !",
      error: "Une erreur est survenue. Veuillez réessayer.",
      namePlaceholder: "Jean Dupont",
      emailPlaceholder: "jean@exemple.fr",
      messagePlaceholder: "Partagez quelques détails sur votre projet, votre rôle ou votre question.",
    },
    footer: {
      rights: "Tous droits réservés.",
      visits: "Visites du Site",
    },
    ui: {
      welcome: "Bienvenue sur mon portfolio",
      getInTouch: "Contactez-moi",
      viewWork: "Voir mon travail",
      scrollDown: "Défiler vers le bas",
      nationality: "Nationalité",
      born: "Né",
      curiosity: "Curiosité",
      innovation: "Innovation",
      drivenBy: "Animé par",
      focusedOn: "Axé sur",
    }
  },
};
