import type { Language, TranslationData } from "../types/language.types";

export const COMMON_INFO = {
  name: "Daniel NIYOMUGENGA",
  email: "daniel.succeeder@gmail.com",
  phone: "+250 791832842",
  address: "KN 183 ST, KN 222 ST, Kigali, Rwanda",
  nationality: "Rwandan",
  dob: "June 16",
  gender: "Male",
  profileImage: {
    src: "/images/profile.jpg",
    alt: "Portrait of Daniel Niyomugenga",
    width: 640,
    height: 960,
  },
  socials: [
    { name: "LinkedIn", url: "https://www.linkedin.com/in/daniel-niyomugenga/" },
    { name: "GitHub", url: "https://github.com/danielstriver" },
    { name: "Instagram", url: "https://www.instagram.com/danielthepentester/" },
    { name: "Email", url: "mailto:daniel.succeeder@gmail.com" },
  ],
};

export const DATA: Record<Language, TranslationData> = {
  en: {
    title: "Full-Stack Engineer & Prompt Engineer",
    about: "I grew up in Rwanda and completed A-Level with a focus on Mathematics, Physics, and Computer Science at New Life Christian High School — where I also led the CS Club and ran coding sessions for fellow students.\n\nI am currently pursuing a BSc in Computer Science at the University of Rwanda, College of Science and Technology. Along the way I have conducted hands-on robotics research at AIMS, earned a Cybersecurity certification from ISC2, and competed in tech initiatives with A2SV.\n\nMy obsession today is simple: leverage agentic AI tools — Claude CLI, Gemini CLI, and Codex CLI — to ship real products in the minimum possible time. I believe the edge in the AI age is no longer how fast you code. It is how well you judge what to build.",
    experience: [
      {
        title: "Robotics Team Leader (CUE Robot Research)",
        company: "TechRise Rwanda",
        location: "Kigali, Rwanda",
        period: "Nov 2024 – Feb 2025",
        description: [
          "Led a research team studying the CUE robot.",
          "Explored history, functionality, and programming.",
          "Conducted testing using pre-coded challenges.",
          "Presented findings and insights to stakeholders.",
        ],
      },
      {
        title: "President of the Computer Department Science Club",
        company: "New Life Christian High School",
        location: "Kigali, Rwanda",
        period: "Oct 2023 – Jul 2024",
        description: [
          "Led a team in developing simple web-based projects.",
          "Designed and implemented basic front-end and back-end web solutions.",
          "Organized and facilitated coding sessions for fellow students.",
          "Provided technical guidance on HTML, CSS, and JavaScript fundamentals.",
          "Managed project timelines and ensured team collaboration.",
        ],
      },
      {
        title: "Robotics & Programming Trainee",
        company: "African Institute for Mathematical Sciences (AIMS)",
        location: "Kigali, Rwanda",
        period: "Mar 2022 – Jul 2023",
        description: [
          "Hands-on robotics programming working with sensors, motors, and microcontrollers.",
          "Applied programming skills to robotics challenges.",
          "Collaborated on real-world robotics applications.",
        ],
      },
      {
        title: "Cybersecurity Fundamentals Trainee",
        company: "ISC2",
        location: "Kigali, Rwanda",
        period: "Aug 2022 – Sep 2022",
        description: [
          "Completed the Certified in Cybersecurity (CC) course.",
          "Gained foundational knowledge in network security and threat analysis.",
          "Learned incident response and security best practices.",
        ],
      },
    ],
    education: [
      {
        degree: "BSc in Computer Science",
        institution: "University of Rwanda, College of Science and Technology",
        period: "2024 – Present",
        website: "https://ur.ac.rw/",
      },
      {
        degree: "Advanced General Certificate of Secondary Education",
        institution: "New Life Christian High School",
        period: "2021 – 2024",
        website: "https://nlca.ac.rw/",
      },
    ],
    projects: [
      {
        title: "Rwanda Tourist Assistant",
        problem: "Planning a Rwanda trip is overwhelming — too many options, zero personalised guidance.",
        description: "A RAG-powered AI travel companion delivering instant, personalised recommendations across 100+ curated Rwandan destinations. Filter by experience type (Nature, Culture, Adventure), budget, and trip duration — in English, French, or Kinyarwanda. Backed by vector search and rate-limited serverless inference.",
        target: "Tourists & travellers exploring Rwanda",
        image: "/images/rwanda-tour-image.jpg",
        link: "https://rwanda-tour-ai.vercel.app",
        github: "https://github.com/danielstriver/rwanda-tour-ai",
        tags: ["React 19", "TypeScript", "Hugging Face", "Supabase Vector", "Upstash Redis", "Vercel"],
        type: "Solo",
      },
      {
        title: "PowerSync",
        problem: "Entering a 20-digit token every time you buy electricity — in the dark, every single time.",
        description: "A smart microgrid platform that activates electricity instantly the moment you pay via mobile money. No token. No waiting. No squinting at numbers in the dark. Buy from your phone, power flows immediately — built for every Rwandan household.",
        target: "Every electricity user in Rwanda",
        image: "/images/project2-image.jpeg",
        link: "https://powersync-rw.vercel.app/",
        github: "https://github.com/danielstriver/powersync",
        tags: ["Next.js", "TypeScript", "IoT", "Mobile Money", "Solar"],
        type: "Team",
      },
      {
        title: "Next Project",
        description: "Something new is being built. Robotics meets real-world problem solving — stay tuned.",
        image: "/images/logo.png",
        status: "Coming Soon",
      },
    ],
    gallery: [
      {
        src: "/images/Gallery/scratch-competition.jpg",
        alt: "Daniel presenting at the Scratch programming competition",
        caption: "Scratch Programming Competition",
      },
      {
        src: "/images/Gallery/techrise-stem-us-embassy.jpeg",
        alt: "Daniel at TechRise STEM training, US Embassy American Center, Kigali",
        caption: "TechRise STEM Training — US Embassy, Kigali",
      },
      {
        src: "/images/Gallery/norrsken-late-night.jpeg",
        alt: "Late-night coding session at Norrsken House Kigali",
        caption: "Late-Night Build Session — Norrsken House",
      },
    ],
    certifications: [
      { name: "Certified in Cybersecurity (CC)", issuer: "ISC2", year: 2022 },
      { name: "IOC Learning Sprint Certificate", issuer: "IOC Young Leaders", year: 2024 },
      { name: "iLead Leadership Certificate", issuer: "Maxwell Leadership Foundation", year: 2024 },
      { name: "Robotics Experiential Learning Certificate", issuer: "AIMS", year: 2023 },
      { name: "Science Club Certificate", issuer: "New Life Christian High School", year: 2024 },
    ],
    skills: [
      { category: "AI & Prompt Engineering", items: ["Claude CLI", "Gemini CLI", "Codex CLI", "LLM APIs", "RAG", "Agentic Workflows", "Prompt Design"] },
      { category: "Languages", items: ["TypeScript", "JavaScript", "Python", "HTML", "CSS"] },
      { category: "Frameworks & Libraries", items: ["React 19", "Next.js", "Node.js", "Express.js", "Tailwind CSS", "Framer Motion"] },
      { category: "Databases & Backend", items: ["PostgreSQL", "Supabase", "SQLite", "Upstash Redis", "Vector Search", "Edge Functions"] },
      { category: "Cloud & DevOps", items: ["Vercel", "Git", "GitHub", "REST APIs", "Vite"] },
      { category: "Robotics & Hardware", items: ["Arduino", "Microcontrollers", "Sensors", "Motors", "C++"] },
      { category: "Spoken Languages", items: ["Kinyarwanda (Native)", "English (C1)", "French (Intermediate)"] },
    ],
    nav: {
      about: "About",
      experience: "Experience",
      projects: "Projects",
      skills: "Skills",
      education: "Education",
      gallery: "Gallery",
      contact: "Contact",
      hireMe: "Say Hello",
    },
    sections: {
      experience: "Professional Experience",
      experienceTagline: "From high school coding clubs to robotics labs — building the foundation one role at a time.",
      projects: "Featured Projects",
      projectsTagline: "Real products solving real problems — shipped from Rwanda, for Rwanda and beyond.",
      gallery: "Moments & Memories",
      skills: "Skills & Expertise",
      skillsTagline: "Full-stack foundations, prompt engineering as a superpower, and a robotics background to keep it grounded.",
      education: "Education & Certifications",
      contact: "Get in Touch",
      about: "About Me",
      academic: "Academic Path",
      certifications: "Certifications",
    },
    contact: {
      title: "Get in Touch",
      subtitle: "Open to internships & collaborations",
      description: "Interested in part-time internships, collaborative builds, or just want to talk tech? Whether you have a project idea, an opportunity to share, or simply want to say hello — I'd love to hear from you.",
      name: "Your Name",
      email: "Email Address",
      phone: "Phone",
      address: "Address",
      subject: "Subject",
      message: "Message",
      send: "Send Message",
      sending: "Sending message...",
      success: "Message sent successfully!",
      error: "Something went wrong. Please try again.",
      namePlaceholder: "John Doe",
      emailPlaceholder: "john@example.com",
      messagePlaceholder: "Share a few details about your project, role, or question.",
    },
    footer: {
      rights: "All rights reserved.",
      visits: "Website Visits",
    },
    ui: {
      welcome: "Welcome to my portfolio",
      getInTouch: "Get in touch",
      viewWork: "View Projects",
      scrollDown: "Scroll Down",
      nationality: "Nationality",
      born: "Born",
      curiosity: "Curiosity",
      innovation: "Innovation",
      drivenBy: "Driven by",
      focusedOn: "Focused on",
      heroTagline: "Building production-grade web apps with React & TypeScript — shipping at AI speed using Claude CLI, Gemini CLI & Codex CLI.",
      aboutLabel: "// about me",
      aboutHeadlineMain: "Student. Builder.",
      aboutHeadlineAccent: "AI-Native.",
      aboutStat: "5+",
      aboutStatLabel: "Certifications & Awards",
      aboutTags: "CS @ University of Rwanda|ISC2 Certified|Robotics Research|Rwanda 🇷🇼|AI-Native Builder ⚡",
      viewLive: "Live Demo",
      viewCode: "View Code",
      soloProject: "Solo",
      teamProject: "Team",
      builtFor: "For:",
      beyondCodeLabel: "// beyond code",
      beyondCodeHeadline: "When I'm not building",
      beyondCodeCopy: "You'll find me running Kigali's hills, walking the premium district near the Convention Centre, or at a car show catching the latest models. I believe the best engineers stay curious — and staying in motion keeps the ideas flowing.",
      beyondCodeTags: "🏃 Running|🚶 Walking Kigali|🚗 Car Shows|🌆 City Exploring|☕ Coffee Chats|📚 Reading",
    }
  },
  rw: {
    title: "Injeniyeri y'Imbuga & Injeniyeri ya Prompt",
    about: "Navutse no gukura mu Rwanda kandi narangirije amashuri yisumbuye nifashishije Matematike, Fiziki na Mudasobwa muri New Life Christian High School — aho nayoboye kandi Club ya Siyansi ya Mudasobwa kandi nateguye amasomo yo guporogaramu.\n\nNoneho niga BSc muri Siyansi ya Mudasobwa kuri Kaminuza y'u Rwanda, Koleji ya Siyansi na Tekinoloji. Mu guherereza amashuri yanjye, nakoze ubushakashatsi bw'imashini zikora muri AIMS, nabonye impamyabumenyi ya Cybersecurity muri ISC2, kandi nafatanyije mu bikorwa bya tekinoloji bya A2SV.\n\nIbyo ndashishikarizwa ubu ni ibi: gukoresha ibikoresho by'AI agentique — Claude CLI, Gemini CLI, na Codex CLI — kugira ngo nubake ibicuruzwa by'ukuri mu gihe gito bishoboka. Nizeye ko icyatandukanya muri iyi myaka ya AI si uko ubaka vuba, ahubwo ni uburyo wategura neza ibyo ubaka.",
    experience: [
      {
        title: "Umuyobozi w'Ikipe ya Robotics (Ubushakashatsi kuri CUE Robot)",
        company: "TechRise Rwanda",
        location: "Kigali, Rwanda",
        period: "Ugushyingo 2024 – Gashyantare 2025",
        description: [
          "Nayoboye ikipe y'ubushakashatsi yigaga kuri robot ya CUE.",
          "Nasesenguye amateka, imikorere, n'uburyo bwo kuyiporogaramu.",
          "Nakoze isuzuma nifashishije imbogamizi zabonetse mbere.",
          "Nerekanye ibyavuye mu bushakashatsi n'inyandiko ku bafatanyabikorwa.",
        ],
      },
      {
        title: "Perezida wa Club ya Siyansi ya Mudasobwa",
        company: "New Life Christian High School",
        location: "Kigali, Rwanda",
        period: "Ukwakira 2023 – Nyakanga 2024",
        description: [
          "Nayoboye ikipe mu gukora imishinga yoroheje yo kuri murandasi.",
          "Nakoze kandi nshyira mu bikorwa uburyo bw'imbere n'inyuma bw'imbuga za murandasi.",
          "Nateguye kandi nayoboye amasomo yo gukora porogaramu ku bandi banyeshuri.",
          "Natanze ubujyanama mu bya tekiniki kuri HTML, CSS, na JavaScript.",
          "Nacunze igihe cy'imishinga kandi nemeza ubufatanye mu ikipe.",
        ],
      },
      {
        title: "Inararibonye mu by'Imashini na Porogaramu",
        company: "African Institute for Mathematical Sciences (AIMS)",
        location: "Kigali, Rwanda",
        period: "Werurwe 2022 – Nyakanga 2023",
        description: [
          "Nakoze imyitozo ngiro mu guporogaramu imashini nifashishije utwumvirizo, moteri, na mikoro-ntumwa.",
          "Nashyize mu bikorwa ubumenyi bwo guporogaramu mu mbogamizi z'imashini zikora.",
          "Nafatanyije n'abandi mu gukora imashini zikoreshwa mu buzima busanzwe.",
        ],
      },
      {
        title: "Amahugurwa y'Ibanze muri Cybersecurity",
        company: "ISC2",
        location: "Kigali, Rwanda",
        period: "Kanama 2022 – Nzeri 2022",
        description: [
          "Narangiye amasomo ya Certified in Cybersecurity (CC).",
          "Nabonye ubumenyi bw'ibanze mu mutekano w'urusobe n'isesengura ry'ibishobora guhungabanya umutekano.",
          "Nize uburyo bwo gutabara igihe habaye ikibazo n'uburyo bwiza bwo kurinda umutekano.",
        ],
      },
    ],
    education: [
      {
        degree: "Baccalauréat muri Siyansi ya Mudasobwa",
        institution: "Kaminuza y'u Rwanda, Koleji ya Siyansi na Tekinoloji",
        period: "2024 – Ubu",
        website: "https://ur.ac.rw/",
      },
      {
        degree: "Impamyabumenyi y'Amashuri Yisumbuye mu masomo rusange",
        institution: "New Life Christian High School",
        period: "2021 – 2024",
        website: "https://nlca.ac.rw/",
      },
    ],
    projects: [
      {
        title: "Rwanda Tourist Assistant",
        problem: "Gutegura urugendo mu Rwanda birashobora kuba bigoye — ahantu henshi, ubuyobozi buke.",
        description: "Inshuti y'ingendo igumana AI ishingiye kuri RAG itanga inama z'urugendo zihariye ku hantu 100+ mu Rwanda. Hitamo uburambe (Imvura, Umuco, Akanyamuneza), ingengo y'imari, n'igihe cy'urugendo — mu Kinyarwanda, Icyongereza, cyangwa Igifaransa.",
        target: "Abakerarugendo baza gusura u Rwanda",
        image: "/images/rwanda-tour-image.jpg",
        link: "https://rwanda-tour-ai.vercel.app",
        github: "https://github.com/danielstriver/rwanda-tour-ai",
        tags: ["React 19", "TypeScript", "Hugging Face", "Supabase Vector", "Upstash Redis", "Vercel"],
        type: "Solo",
      },
      {
        title: "PowerSync",
        problem: "Gushyira imibare 20 buri gihe ugura amashanyarazi — nijoro, mu mwijima.",
        description: "Urubuga rw'imishinga y'ingufu ishingiye kuri microgrid igufasha gutera amashanyarazi ako kanya urangije kwishyura amafaranga yawe kuri telefone. Nta nimero. Nta gutegereza. Gura kuri telefone yawe, amashanyarazi atangira ako kanya — yubatswe ku Munyarwanda wese.",
        target: "Abakoresha amashanyarazi bose mu Rwanda",
        image: "/images/project2-image.jpeg",
        link: "https://powersync-rw.vercel.app/",
        github: "https://github.com/danielstriver/powersync",
        tags: ["Next.js", "TypeScript", "IoT", "Mobile Money", "Solar"],
        type: "Team",
      },
      {
        title: "Umushinga Uhatsi",
        description: "Ikintu gishya kirimo gushyirwa hamwe. Robotics ihuza n'ibibazo by'ukuri — komeza urebe.",
        image: "/images/logo.png",
        status: "Uzaza vuba",
      },
    ],
    gallery: [
      {
        src: "/images/Gallery/scratch-competition.jpg",
        alt: "Daniel agaragaza umushinga wa Scratch mu rushanwa",
        caption: "Rushanwa rwa Porogaramu ya Scratch",
      },
      {
        src: "/images/Gallery/techrise-stem-us-embassy.jpeg",
        alt: "Daniel mu mahugurwa ya TechRise STEM, Ambasade y'Amerika, Kigali",
        caption: "Amahugurwa ya TechRise STEM — Ambasade y'Amerika, Kigali",
      },
      {
        src: "/images/Gallery/norrsken-late-night.jpeg",
        alt: "Gukorera ijoro mu Norrsken House Kigali",
        caption: "Gukorera Ijoro — Norrsken House",
      },
    ],
    certifications: [
      { name: "Impamyabumenyi muri Cybersecurity (CC)", issuer: "ISC2", year: 2022 },
      { name: "Icyemezo cya IOC Learning Sprint", issuer: "IOC Young Leaders", year: 2024 },
      { name: "Icyemezo cy'Ubuhanga mu Buyobozi (iLead)", issuer: "Maxwell Leadership Foundation", year: 2024 },
      { name: "Icyemezo cy'imyitozo ngiro mu by'imashini zikora", issuer: "AIMS", year: 2023 },
      { name: "Icyemezo cya Club ya Siyansi", issuer: "New Life Christian High School", year: 2024 },
    ],
    skills: [
      { category: "AI & Prompt Engineering", items: ["Claude CLI", "Gemini CLI", "Codex CLI", "LLM APIs", "RAG", "Inzira z'AI", "Prompt Design"] },
      { category: "Indimi zo Guporogaramu", items: ["TypeScript", "JavaScript", "Python", "HTML", "CSS"] },
      { category: "Inzego & Biblioteki", items: ["React 19", "Next.js", "Node.js", "Express.js", "Tailwind CSS", "Framer Motion"] },
      { category: "Imbuga z'Amakuru & Backend", items: ["PostgreSQL", "Supabase", "SQLite", "Upstash Redis", "Vector Search", "Edge Functions"] },
      { category: "Cloud & DevOps", items: ["Vercel", "Git", "GitHub", "REST APIs", "Vite"] },
      { category: "Robotics & Donanım", items: ["Arduino", "Mikoro-ntumwa", "Utwumvirizo", "Moteri", "C++"] },
      { category: "Indimi Mvugwa", items: ["Ikinyarwanda (Ururimi kavukire)", "Icyongereza (C1)", "Igifaransa (Hagati)"] },
    ],
    nav: {
      about: "Ibyanjye",
      experience: "Inararibonye",
      projects: "Imishinga",
      skills: "Ubumenyi",
      education: "Amashuri",
      gallery: "Igalari",
      contact: "Twandikire",
      hireMe: "Bwira Muraho",
    },
    sections: {
      experience: "Inararibonye mu Kazi",
      experienceTagline: "Kuva mu mashuri yisumbuye kugeza mu laboratwari za robotics — kubaka inkingi inzira imwe na imwe.",
      projects: "Imishinga Y'ingenzi",
      projectsTagline: "Ibicuruzwa by'ukuri bikemura ibibazo by'ukuri — byubatswe mu Rwanda, ku Rwanda no hanze.",
      gallery: "Ibihe n'Inzibutso",
      skills: "Ubumenyi n'Ubuhanga",
      skillsTagline: "Inkingi za full-stack, prompt engineering nk'intwaro ikomeye, n'inararibonye ya robotics.",
      education: "Amashuri n'Impamyabumenyi",
      contact: "Tuvugane",
      about: "Njyewe mwayo",
      academic: "Amashuri Nize",
      certifications: "Impamyabumenyi",
    },
    contact: {
      title: "Tuvugane",
      subtitle: "Ndashaka amahugurwa no gukorera hamwe",
      description: "Naba ushaka amahugurwa yo igice cy'igihe, gukorera hamwe ku mushinga, cyangwa gusa kuganira ku ikoranabuhanga? Naba ufite igitekerezo, amahirwe, cyangwa ushaka gusa kuramukanya — nzishimira gukomezanya nawe.",
      name: "Izina ryawe",
      email: "Imeri yawe",
      phone: "Telefoni",
      address: "Aho uherereye",
      subject: "Icyo uvugaho",
      message: "Ubutumwa",
      send: "Ohereza Ubutumwa",
      sending: "Ubutumwa buracyoherezwa...",
      success: "Ubutumwa bwoherejwe neza!",
      error: "Hagize ikibazo kiba. Ongera ugerageze.",
      namePlaceholder: "Izina ryawe hano",
      emailPlaceholder: "imeri@urubuga.rw",
      messagePlaceholder: "Andika ubutumwa bwawe hano...",
    },
    footer: {
      rights: "Uburenganzira bwose burasigasigwa.",
      visits: "Abasuye Urubuga",
    },
    ui: {
      welcome: "Murakaza neza ku rubuga rwanjye",
      getInTouch: "Tuvugane",
      viewWork: "Reba Imishinga",
      scrollDown: "Manuka Hasi",
      nationality: "Ubwenegihugu",
      born: "Yavutse",
      curiosity: "Amatsiko",
      innovation: "Iguhoraho",
      drivenBy: "Biyobowe n'",
      focusedOn: "Bishingiye ku",
      heroTagline: "Nubaka ibikorwa bya murandasi nifashishije React & TypeScript — nkabita vuba nifashishije Claude CLI, Gemini CLI & Codex CLI.",
      aboutLabel: "// ibyerekeye njye",
      aboutHeadlineMain: "Umunyeshuri. Ubaka.",
      aboutHeadlineAccent: "AI-Native.",
      aboutStat: "5+",
      aboutStatLabel: "Impamyabumenyi & Ibihembo",
      aboutTags: "CS @ Kaminuza y'u Rwanda|ISC2 Certified|Ubushakashatsi bw'Imashini|u Rwanda 🇷🇼|Ubaka na AI ⚡",
      viewLive: "Reba Urubuga",
      viewCode: "Reba Code",
      soloProject: "Wenyine",
      teamProject: "Ikipe",
      builtFor: "Yubatswe kuri:",
      beyondCodeLabel: "// hanze y'amakode",
      beyondCodeHeadline: "Igihe ntubaka",
      beyondCodeCopy: "Ubona nkora joginge ku misozi ya Kigali, ngerageza inzira za CBD hafi ya Convention Centre, cyangwa mu marushanwa y'imodoka. Nizeye ko injeniyeri nziza zisigara zifite ubushake — kuguma mu ngendo bitera ibitekerezo bishya.",
      beyondCodeTags: "🏃 Joginge|🚶 Kugenda Kigali|🚗 Marushanwa y'Imodoka|🌆 Gushakashaka Umujyi|☕ Ikiganiro na Kawa|📚 Gusoma",
    }
  },
  fr: {
    title: "Ingénieur Full-Stack & Ingénieur Prompt",
    about: "J'ai grandi au Rwanda et j'ai terminé le lycée avec une spécialisation en Mathématiques, Physique et Informatique à la New Life Christian High School — où j'ai également dirigé le Club Informatique et organisé des sessions de codage pour mes camarades.\n\nJe poursuis actuellement un BSc en Informatique à l'Université du Rwanda, Collège des Sciences et Technologies. En parallèle, j'ai mené des recherches en robotique à l'AIMS, obtenu une certification en Cybersécurité de l'ISC2, et participé aux initiatives technologiques d'A2SV.\n\nMon obsession aujourd'hui est simple : utiliser les outils d'IA agentique — Claude CLI, Gemini CLI et Codex CLI — pour livrer de vrais produits dans le minimum de temps possible. Je crois que l'avantage dans l'ère de l'IA n'est plus la vitesse de codage, mais la qualité du jugement sur ce qu'il faut construire.",
    experience: [
      {
        title: "Chef d'équipe Robotique (Recherche Robot CUE)",
        company: "TechRise Rwanda",
        location: "Kigali, Rwanda",
        period: "Nov 2024 – Fév 2025",
        description: [
          "Direction d'une équipe de recherche étudiant le robot CUE.",
          "Exploration de l'histoire, de la fonctionnalité et de la programmation.",
          "Réalisation de tests à l'aide de défis pré-codés.",
          "Présentation des résultats et des perspectives aux parties prenantes.",
        ],
      },
      {
        title: "Président du club scientifique du département informatique",
        company: "New Life Christian High School",
        location: "Kigali, Rwanda",
        period: "Oct 2023 – Juil 2024",
        description: [
          "Direction d'une équipe dans le développement de projets web simples.",
          "Conception et mise en œuvre de solutions web front-end et back-end de base.",
          "Organisation et animation de sessions de codage pour les étudiants.",
          "Conseils techniques sur les bases du HTML, CSS et JavaScript.",
          "Gestion des délais de projet et garantie de la collaboration d'équipe.",
        ],
      },
      {
        title: "Stagiaire en Robotique et Programmation",
        company: "African Institute for Mathematical Sciences (AIMS)",
        location: "Kigali, Rwanda",
        period: "Mar 2022 – Juil 2023",
        description: [
          "Programmation robotique pratique avec capteurs, moteurs et microcontrôleurs.",
          "Application des compétences en programmation aux défis de la robotique.",
          "Collaboration sur des applications robotiques réelles.",
        ],
      },
      {
        title: "Stagiaire en Fondamentaux de la Cybersécurité",
        company: "ISC2",
        location: "Kigali, Rwanda",
        period: "Août 2022 – Sept 2022",
        description: [
          "Cours Certified in Cybersecurity (CC) terminé.",
          "Connaissances de base en sécurité réseau et analyse des menaces.",
          "Apprentissage de la réponse aux incidents et des meilleures pratiques de sécurité.",
        ],
      },
    ],
    education: [
      {
        degree: "Licence en Informatique",
        institution: "Université du Rwanda, Collège des Sciences et Technologies",
        period: "2024 – Présent",
        website: "https://ur.ac.rw/",
      },
      {
        degree: "Certificat Général Avancé d'Enseignement Secondaire",
        institution: "New Life Christian High School",
        period: "2021 – 2024",
        website: "https://nlca.ac.rw/",
      },
    ],
    projects: [
      {
        title: "Rwanda Tourist Assistant",
        problem: "Planifier un voyage au Rwanda est complexe — trop d'options, aucun guide personnalisé.",
        description: "Un compagnon de voyage IA alimenté par RAG qui fournit des recommandations instantanées et personnalisées pour plus de 100 destinations rwandaises. Filtrez par type d'expérience (Nature, Culture, Aventure), budget et durée — en français, anglais ou kinyarwanda.",
        target: "Touristes & voyageurs qui explorent le Rwanda",
        image: "/images/rwanda-tour-image.jpg",
        link: "https://rwanda-tour-ai.vercel.app",
        github: "https://github.com/danielstriver/rwanda-tour-ai",
        tags: ["React 19", "TypeScript", "Hugging Face", "Supabase Vector", "Upstash Redis", "Vercel"],
        type: "Solo",
      },
      {
        title: "PowerSync",
        problem: "Saisir un code de 20 chiffres à chaque achat d'électricité — dans le noir, chaque fois.",
        description: "Une plateforme de microgrids intelligents qui active l'électricité instantanément dès que vous payez via mobile money. Aucun code. Aucune attente. Payez depuis votre téléphone, le courant arrive immédiatement — conçu pour chaque Rwandais.",
        target: "Tous les utilisateurs d'électricité au Rwanda",
        image: "/images/project2-image.jpeg",
        link: "https://powersync-rw.vercel.app/",
        github: "https://github.com/danielstriver/powersync",
        tags: ["Next.js", "TypeScript", "IoT", "Mobile Money", "Solar"],
        type: "Team",
      },
      {
        title: "Prochain Projet",
        description: "Quelque chose de nouveau est en construction. La robotique rencontre des problèmes réels — restez connecté.",
        image: "/images/logo.png",
        status: "Prochainement",
      },
    ],
    gallery: [
      {
        src: "/images/Gallery/scratch-competition.jpg",
        alt: "Daniel présentant un projet Scratch en compétition",
        caption: "Compétition de Programmation Scratch",
      },
      {
        src: "/images/Gallery/techrise-stem-us-embassy.jpeg",
        alt: "Daniel lors de la formation TechRise STEM, Centre Américain de l'Ambassade US, Kigali",
        caption: "Formation TechRise STEM — Ambassade US, Kigali",
      },
      {
        src: "/images/Gallery/norrsken-late-night.jpeg",
        alt: "Session de code tardive à Norrsken House Kigali",
        caption: "Session de Code en Soirée — Norrsken House",
      },
    ],
    certifications: [
      { name: "Certifié en Cybersécurité (CC)", issuer: "ISC2", year: 2022 },
      { name: "Certificat d'apprentissage IOC", issuer: "Jeunes leaders du CIO", year: 2024 },
      { name: "Certificat de Leadership iLead", issuer: "Fondation Maxwell Leadership", year: 2024 },
      { name: "Certificat d'apprentissage en robotique", issuer: "AIMS", year: 2023 },
      { name: "Certificat du club scientifique", issuer: "New Life Christian High School", year: 2024 },
    ],
    skills: [
      { category: "IA & Prompt Engineering", items: ["Claude CLI", "Gemini CLI", "Codex CLI", "APIs LLM", "RAG", "Workflows Agentiques", "Prompt Design"] },
      { category: "Langages", items: ["TypeScript", "JavaScript", "Python", "HTML", "CSS"] },
      { category: "Frameworks & Bibliothèques", items: ["React 19", "Next.js", "Node.js", "Express.js", "Tailwind CSS", "Framer Motion"] },
      { category: "Bases de Données & Backend", items: ["PostgreSQL", "Supabase", "SQLite", "Upstash Redis", "Recherche Vectorielle", "Edge Functions"] },
      { category: "Cloud & DevOps", items: ["Vercel", "Git", "GitHub", "REST APIs", "Vite"] },
      { category: "Robotique & Matériel", items: ["Arduino", "Microcontrôleurs", "Capteurs", "Moteurs", "C++"] },
      { category: "Langues Parlées", items: ["Kinyarwanda (Langue maternelle)", "Anglais (C1)", "Français (Intermédiaire)"] },
    ],
    nav: {
      about: "À Propos",
      experience: "Expérience",
      projects: "Projets",
      skills: "Compétences",
      education: "Éducation",
      gallery: "Galerie",
      contact: "Contact",
      hireMe: "Dire Bonjour",
    },
    sections: {
      experience: "Expérience Professionnelle",
      experienceTagline: "Du club informatique du lycée aux laboratoires de robotique — construire les bases, une étape à la fois.",
      projects: "Projets Phares",
      projectsTagline: "Des produits réels pour des problèmes réels — conçus au Rwanda, pour le Rwanda et au-delà.",
      gallery: "Moments & Souvenirs",
      skills: "Compétences & Expertise",
      skillsTagline: "Bases full-stack solides, prompt engineering comme superpouvoir, et une expérience robotique pour rester ancré dans le réel.",
      education: "Éducation & Certifications",
      contact: "Contactez-moi",
      about: "À Propos",
      academic: "Parcours Académique",
      certifications: "Certifications",
    },
    contact: {
      title: "Contactez-moi",
      subtitle: "Ouvert aux stages et collaborations",
      description: "Intéressé par des stages à temps partiel, des projets collaboratifs, ou simplement envie de parler tech ? Que vous ayez une idée de projet, une opportunité à partager, ou juste envie de dire bonjour — j'adorerais vous lire.",
      name: "Votre Nom",
      email: "Adresse Email",
      phone: "Téléphone",
      address: "Adresse",
      subject: "Sujet",
      message: "Message",
      send: "Envoyer le Message",
      sending: "Envoi du message...",
      success: "Message envoyé avec succès !",
      error: "Une erreur est survenue. Veuillez réessayer.",
      namePlaceholder: "Jean Dupont",
      emailPlaceholder: "jean@exemple.fr",
      messagePlaceholder: "Partagez quelques détails sur votre projet, votre rôle ou votre question.",
    },
    footer: {
      rights: "Tous droits réservés.",
      visits: "Visites du Site",
    },
    ui: {
      welcome: "Bienvenue sur mon portfolio",
      getInTouch: "Contactez-moi",
      viewWork: "Voir mes Projets",
      scrollDown: "Défiler vers le bas",
      nationality: "Nationalité",
      born: "Né",
      curiosity: "Curiosité",
      innovation: "Innovation",
      drivenBy: "Animé par",
      focusedOn: "Axé sur",
      heroTagline: "Je développe des applications web performantes avec React & TypeScript — et les livre à la vitesse de l'IA grâce à Claude CLI, Gemini CLI & Codex CLI.",
      aboutLabel: "// à propos de moi",
      aboutHeadlineMain: "Étudiant. Bâtisseur.",
      aboutHeadlineAccent: "AI-Natif.",
      aboutStat: "5+",
      aboutStatLabel: "Certifications & Prix",
      aboutTags: "CS @ Univ. du Rwanda|Certifié ISC2|Recherche en Robotique|Rwanda 🇷🇼|Bâtisseur AI ⚡",
      viewLive: "Démo Live",
      viewCode: "Voir le Code",
      soloProject: "Solo",
      teamProject: "Équipe",
      builtFor: "Pour :",
      beyondCodeLabel: "// au-delà du code",
      beyondCodeHeadline: "Quand je ne construis pas",
      beyondCodeCopy: "Vous me trouverez en train de courir dans les collines de Kigali, de parcourir le quartier premium près du Centre de Conférences, ou à un show automobile pour voir les derniers modèles. Je crois que les meilleurs ingénieurs restent curieux — et rester en mouvement, c'est garder les idées vivantes.",
      beyondCodeTags: "🏃 Running|🚶 Marche à Kigali|🚗 Shows Automobiles|🌆 Explorer la Ville|☕ Cafés Talks|📚 Lecture",
    }
  },
};
