import type { Language, TranslationData } from "../types/language.types";

export const COMMON_INFO = {
  name: "Daniel NIYOMUGENGA",
  email: "daniel.succeeder@gmail.com",
  phone: "+250 791832842",
  whatsappUrl: "https://wa.me/250791832842",
  address: "KN 183 ST, KN 222 ST, Kigali, Rwanda",
  nationality: "Rwandan",
  dob: "June 16",
  gender: "Male",
  profileImage: {
    src: "/images/profile.jpg",
    alt: "Portrait of Daniel Niyomugenga",
    width: 640,
    height: 960,
  },
  socials: [
    { name: "LinkedIn", url: "https://www.linkedin.com/in/daniel-niyomugenga/" },
    { name: "GitHub", url: "https://github.com/danielstriver" },
    { name: "Instagram", url: "https://www.instagram.com/danielthepentester/" },
    { name: "Email", url: "mailto:daniel.succeeder@gmail.com" },
  ],
};

export const DATA: Record<Language, TranslationData> = {
  en: {
    title: "Full-Stack Engineer & Prompt Engineer",
    about: "I grew up in Rwanda and completed A-Level with a focus on Mathematics, Physics, and Computer Science at New Life Christian High School — where I also led the CS Club and ran coding sessions for fellow students.\n\nI am currently pursuing a BSc in Computer Science at the University of Rwanda, College of Science and Technology. Along the way I have conducted hands-on robotics research at AIMS, earned a Cybersecurity certification from ISC2, and competed in tech initiatives with A2SV.\n\nMy obsession today is simple: leverage agentic AI tools — Claude CLI, Gemini CLI, and Codex CLI — to ship real products in the minimum possible time. I believe the edge in the AI age is no longer how fast you code. It is how well you judge what to build.",
    experience: [
      {
        title: "Robotics Team Leader (CUE Robot Research)",
        company: "TechRise Rwanda",
        location: "Kigali, Rwanda",
        period: "Nov 2024 – Feb 2025",
        description: [
          "Led a research team studying the CUE robot.",
          "Explored history, functionality, and programming.",
          "Conducted testing using pre-coded challenges.",
          "Presented findings and insights to stakeholders.",
        ],
      },
      {
        title: "President of the Computer Department Science Club",
        company: "New Life Christian High School",
        location: "Kigali, Rwanda",
        period: "Oct 2023 – Jul 2024",
        description: [
          "Led a team in developing simple web-based projects.",
          "Designed and implemented basic front-end and back-end web solutions.",
          "Organized and facilitated coding sessions for fellow students.",
          "Provided technical guidance on HTML, CSS, and JavaScript fundamentals.",
          "Managed project timelines and ensured team collaboration.",
        ],
      },
      {
        title: "Robotics & Programming Trainee",
        company: "African Institute for Mathematical Sciences (AIMS)",
        location: "Kigali, Rwanda",
        period: "Mar 2022 – Jul 2023",
        description: [
          "Hands-on robotics programming working with sensors, motors, and microcontrollers.",
          "Applied programming skills to robotics challenges.",
          "Collaborated on real-world robotics applications.",
        ],
      },
      {
        title: "Cybersecurity Fundamentals Trainee",
        company: "ISC2",
        location: "Kigali, Rwanda",
        period: "Aug 2022 – Sep 2022",
        description: [
          "Completed the Certified in Cybersecurity (CC) course.",
          "Gained foundational knowledge in network security and threat analysis.",
          "Learned incident response and security best practices.",
        ],
      },
    ],
    education: [
      {
        degree: "BSc in Computer Science",
        institution: "University of Rwanda, College of Science and Technology",
        period: "2024 – Present",
        website: "https://ur.ac.rw/",
      },
      {
        degree: "Advanced General Certificate of Secondary Education",
        institution: "New Life Christian High School",
        period: "2021 – 2024",
        website: "https://nlca.ac.rw/",
      },
      {
        degree: "Prompt Engineering & Agentic AI",
        institution: "Self-Directed · Continuous Learning",
        period: "2024 – Present",
        type: "continuous",
        tags: ["Claude API", "Gemini", "Codex", "RAG", "Agentic Workflows", "LLM Design"],
      },
    ],
    projects: [
      {
        title: "Rwanda Tourist Assistant",
        problem: "Planning a Rwanda trip is overwhelming — too many options, zero personalised guidance.",
        description: "A RAG-powered AI travel companion delivering instant, personalised recommendations across 100+ curated Rwandan destinations. Filter by experience type (Nature, Culture, Adventure), budget, and trip duration — in English, French, or Kinyarwanda. Backed by vector search and rate-limited serverless inference.",
        target: "Tourists & travellers exploring Rwanda",
        image: "/images/rwanda-tour-image.jpg",
        link: "https://rwanda-tour-ai.vercel.app",
        github: "https://github.com/danielstriver/rwanda-tour-ai",
        tags: ["React 19", "TypeScript", "Hugging Face", "Supabase Vector", "Upstash Redis", "Vercel"],
        type: "Solo",
      },
      {
        title: "PowerSync",
        problem: "Entering a 20-digit token every time you buy electricity — in the dark, every single time.",
        description: "A smart microgrid platform that activates electricity instantly the moment you pay via mobile money. No token. No waiting. No squinting at numbers in the dark. Buy from your phone, power flows immediately — built for every Rwandan household.",
        target: "Every electricity user in Rwanda",
        image: "/images/project2-image.jpeg",
        link: "https://powersync-rw.vercel.app/",
        github: "https://github.com/danielstriver/powersync",
        tags: ["Next.js", "TypeScript", "IoT", "Mobile Money", "Solar"],
        type: "Team",
      },
      {
        title: "Next Project",
        description: "Something new is being built. Robotics meets real-world problem solving — stay tuned.",
        image: "/images/logo.png",
        status: "Coming Soon",
      },
    ],
    gallery: [
      {
        src: "/images/Gallery/scratch-competition.jpg",
        alt: "Daniel presenting at the Scratch programming competition",
        caption: "Scratch Programming Competition",
      },
      {
        src: "/images/Gallery/techrise-stem-us-embassy.jpeg",
        alt: "Daniel at TechRise STEM training, US Embassy American Center, Kigali",
        caption: "TechRise STEM Training — US Embassy, Kigali",
      },
      {
        src: "/images/Gallery/norrsken-late-night.jpeg",
        alt: "Late-night coding session at Norrsken House Kigali",
        caption: "Late-Night Build Session — Norrsken House",
      },
    ],
    certifications: [
      { name: "Certified in Cybersecurity (CC)", issuer: "ISC2", year: 2022 },
      { name: "IOC Learning Sprint Certificate", issuer: "IOC Young Leaders", year: 2024 },
      { name: "iLead Leadership Certificate", issuer: "Maxwell Leadership Foundation", year: 2024 },
      { name: "Robotics Experiential Learning Certificate", issuer: "AIMS", year: 2023 },
      { name: "Science Club Certificate", issuer: "New Life Christian High School", year: 2024 },
    ],
    skills: [
      { category: "AI & Prompt Engineering", items: ["Claude CLI", "Gemini CLI", "Codex CLI", "LLM APIs", "RAG", "Agentic Workflows", "Prompt Design"] },
      { category: "Languages", items: ["TypeScript", "JavaScript", "Python", "HTML", "CSS"] },
      { category: "Frameworks & Libraries", items: ["React 19", "Next.js", "Node.js", "Express.js", "Tailwind CSS", "Framer Motion"] },
      { category: "Databases & Backend", items: ["PostgreSQL", "Supabase", "SQLite", "Upstash Redis", "Vector Search", "Edge Functions"] },
      { category: "Cloud & DevOps", items: ["Vercel", "Git", "GitHub", "REST APIs", "Vite"] },
      { category: "Robotics & Hardware", items: ["Arduino", "Microcontrollers", "Sensors", "Motors", "C++"] },
      { category: "Spoken Languages", items: ["Kinyarwanda (Native)", "English (C1)", "French (Intermediate)"] },
    ],
    nav: {
      about: "About",
      experience: "Experience",
      projects: "Projects",
      skills: "Skills",
      education: "Education",
      gallery: "Gallery",
      contact: "Contact",
      hireMe: "Say Hello",
    },
    sections: {
      experience: "Professional Experience",
      experienceTagline: "From high school coding clubs to robotics labs — building the foundation one role at a time.",
      projects: "Featured Projects",
      projectsTagline: "Real products solving real problems — shipped from Rwanda, for Rwanda and beyond.",
      gallery: "Moments & Memories",
      skills: "Skills & Expertise",
      skillsTagline: "Full-stack foundations, prompt engineering as a superpower, and a robotics background to keep it grounded.",
      education: "Education & Certifications",
      contact: "Get in Touch",
      about: "About Me",
      academic: "Academic Path",
      certifications: "Certifications",
    },
    contact: {
      title: "Get in Touch",
      subtitle: "Open to internships & collaborations",
      description: "Interested in part-time internships, collaborative builds, or just want to talk tech? Whether you have a project idea, an opportunity to share, or simply want to say hello — I'd love to hear from you.",
      name: "Your Name",
      email: "Email Address",
      phone: "Phone",
      address: "Address",
      subject: "Subject",
      message: "Message",
      send: "Send Message",
      sending: "Sending message...",
      success: "Message sent successfully!",
      error: "Something went wrong. Please try again.",
      namePlaceholder: "John Doe",
      emailPlaceholder: "john@example.com",
      messagePlaceholder: "Share a few details about your project, role, or question.",
    },
    footer: {
      rights: "All rights reserved.",
      visits: "Website Visits",
    },
    ui: {
      welcome: "Welcome to my portfolio",
      getInTouch: "Get in touch",
      viewWork: "View Projects",
      scrollDown: "Scroll Down",
      nationality: "Nationality",
      born: "Born",
      curiosity: "Curiosity",
      innovation: "Innovation",
      drivenBy: "Driven by",
      focusedOn: "Focused on",
      heroTagline: "Building production-grade web apps with React & TypeScript — shipping at AI speed using Claude CLI, Gemini CLI & Codex CLI.",
      aboutLabel: "// about me",
      aboutHeadlineMain: "Student. Builder.",
      aboutHeadlineAccent: "AI-Native.",
      aboutStat: "5+",
      aboutStatLabel: "Certifications & Awards",
      aboutTags: "CS @ University of Rwanda|ISC2 Certified|Robotics Research|Rwanda 🇷🇼|AI-Native Builder ⚡",
      viewLive: "Live Demo",
      viewCode: "View Code",
      soloProject: "Solo",
      teamProject: "Team",
      builtFor: "For:",
      beyondCodeLabel: "// beyond code",
      beyondCodeHeadline: "When I'm not building",
      beyondCodeCopy: "You'll find me running Kigali's hills, walking the premium district near the Convention Centre, or deep in a YouTube rabbit hole watching car shows — new model reveals, reviews, and restomods. I believe the best engineers stay curious — and staying in motion keeps the ideas flowing.",
      beyondCodeTags: "🏃 Running|🚶 Walking Kigali|🚗 YouTube Car Shows|🌆 City Exploring|☕ Coffee Chats|📚 Reading",
    }
  },
  rw: {
    title: "Injeniyeri y'Imbuga & Injeniyeri ya Prompt",
    about: "Navutse no gukura mu Rwanda kandi narangirije amashuri yisumbuye nifashishije Matematike, Fiziki na Mudasobwa muri New Life Christian High School — aho nayoboye kandi Club ya Siyansi ya Mudasobwa kandi nateguye amasomo yo guporogaramu.\n\nNoneho niga BSc muri Siyansi ya Mudasobwa kuri Kaminuza y'u Rwanda, Koleji ya Siyansi na Tekinoloji. Mu guherereza amashuri yanjye, nakoze ubushakashatsi bw'imashini zikora muri AIMS, nabonye impamyabumenyi ya Cybersecurity muri ISC2, kandi nafatanyije mu bikorwa bya tekinoloji bya A2SV.\n\nIbyo ndashishikarizwa ubu ni ibi: gukoresha ibikoresho by'AI agentique — Claude CLI, Gemini CLI, na Codex CLI — kugira ngo nubake ibicuruzwa by'ukuri mu gihe gito bishoboka. Nizeye ko icyatandukanya muri iyi myaka ya AI si uko ubaka vuba, ahubwo ni uburyo wategura neza ibyo ubaka.",
    experience: [
      {
        title: "Umuyobozi w'Ikipe ya Robotics (Ubushakashatsi kuri CUE Robot)",
        company: "TechRise Rwanda",
        location: "Kigali, Rwanda",
        period: "Ugushyingo 2024 – Gashyantare 2025",
        description: [
          "Nayoboye ikipe y'ubushakashatsi yigaga kuri robot ya CUE.",
          "Nasesenguye amateka, imikorere, n'uburyo bwo kuyiporogaramu.",
          "Nakoze isuzuma nifashishije imbogamizi zabonetse mbere.",
          "Nerekanye ibyavuye mu bushakashatsi n'inyandiko ku bafatanyabikorwa.",
        ],
      },
      {
        title: "Perezida wa Club ya Siyansi ya Mudasobwa",
        company: "New Life Christian High School",
        location: "Kigali, Rwanda",
        period: "Ukwakira 2023 – Nyakanga 2024",
        description: [
          "Nayoboye ikipe mu gukora imishinga yoroheje yo kuri murandasi.",
          "Nakoze kandi nshyira mu bikorwa uburyo bw'imbere n'inyuma bw'imbuga za murandasi.",
          "Nateguye kandi nayoboye amasomo yo gukora porogaramu ku bandi banyeshuri.",
          "Natanze ubujyanama mu bya tekiniki kuri HTML, CSS, na JavaScript.",
          "Nacunze igihe cy'imishinga kandi nemeza ubufatanye mu ikipe.",
        ],
      },
      {
        title: "Inararibonye mu by'Imashini na Porogaramu",
        company: "African Institute for Mathematical Sciences (AIMS)",
        location: "Kigali, Rwanda",
        period: "Werurwe 2022 – Nyakanga 2023",
        description: [
          "Nakoze imyitozo ngiro mu guporogaramu imashini nifashishije utwumvirizo, moteri, na mikoro-ntumwa.",
          "Nashyize mu bikorwa ubumenyi bwo guporogaramu mu mbogamizi z'imashini zikora.",
          "Nafatanyije n'abandi mu gukora imashini zikoreshwa mu buzima busanzwe.",
        ],
      },
      {
        title: "Amahugurwa y'Ibanze muri Cybersecurity",
        company: "ISC2",
        location: "Kigali, Rwanda",
        period: "Kanama 2022 – Nzeri 2022",
        description: [
          "Narangiye amasomo ya Certified in Cybersecurity (CC).",
          "Nabonye ubumenyi bw'ibanze mu mutekano w'urusobe n'isesengura ry'ibishobora guhungabanya umutekano.",
          "Nize uburyo bwo gutabara igihe habaye ikibazo n'uburyo bwiza bwo kurinda umutekano.",
        ],
      },
    ],
    education: [
      {
        degree: "Baccalauréat muri Siyansi ya Mudasobwa",
        institution: "Kaminuza y'u Rwanda, Koleji ya Siyansi na Tekinoloji",
        period: "2024 – Ubu",
        website: "https://ur.ac.rw/",
      },
      {
        degree: "Impamyabumenyi y'Amashuri Yisumbuye mu masomo rusange",
        institution: "New Life Christian High School",
        period: "2021 – 2024",
        website: "https://nlca.ac.rw/",
      },
      {
        degree: "Prompt Engineering & AI Agentique",
        institution: "Kwigisha Bwite · Gukomeza Kwiga",
        period: "2024 – Ubu",
        type: "continuous",
        tags: ["Claude API", "Gemini", "Codex", "RAG", "Inzira z'AI", "LLM Design"],
      },
    ],
    projects: [
      {
        title: "Rwanda Tourist Assistant",
        problem: "Gutegura urugendo mu Rwanda birashobora kuba bigoye — ahantu henshi, ubuyobozi buke.",
        description: "Inshuti y'ingendo igumana AI ishingiye kuri RAG itanga inama z'urugendo zihariye ku hantu 100+ mu Rwanda. Hitamo uburambe (Imvura, Umuco, Akanyamuneza), ingengo y'imari, n'igihe cy'urugendo — mu Kinyarwanda, Icyongereza, cyangwa Igifaransa.",
        target: "Abakerarugendo baza gusura u Rwanda",
        image: "/images/rwanda-tour-image.jpg",
        link: "https://rwanda-tour-ai.vercel.app",
        github: "https://github.com/danielstriver/rwanda-tour-ai",
        tags: ["React 19", "TypeScript", "Hugging Face", "Supabase Vector", "Upstash Redis", "Vercel"],
        type: "Solo",
      },
      {
        title: "PowerSync",
        problem: "Gushyira imibare 20 buri gihe ugura amashanyarazi — nijoro, mu mwijima.",
        description: "Urubuga rw'imishinga y'ingufu ishingiye kuri microgrid igufasha gutera amashanyarazi ako kanya urangije kwishyura amafaranga yawe kuri telefone. Nta nimero. Nta gutegereza. Gura kuri telefone yawe, amashanyarazi atangira ako kanya — yubatswe ku Munyarwanda wese.",
        target: "Abakoresha amashanyarazi bose mu Rwanda",
        image: "/images/project2-image.jpeg",
        link: "https://powersync-rw.vercel.app/",
        github: "https://github.com/danielstriver/powersync",
        tags: ["Next.js", "TypeScript", "IoT", "Mobile Money", "Solar"],
        type: "Team",
      },
      {
        title: "Umushinga Uhatsi",
        description: "Ikintu gishya kirimo gushyirwa hamwe. Robotics ihuza n'ibibazo by'ukuri — komeza urebe.",
        image: "/images/logo.png",
        status: "Uzaza vuba",
      },
    ],
    gallery: [
      {
        src: "/images/Gallery/scratch-competition.jpg",
        alt: "Daniel agaragaza umushinga wa Scratch mu rushanwa",
        caption: "Rushanwa rwa Porogaramu ya Scratch",
      },
      {
        src: "/images/Gallery/techrise-stem-us-embassy.jpeg",
        alt: "Daniel mu mahugurwa ya TechRise STEM, Ambasade y'Amerika, Kigali",
        caption: "Amahugurwa ya TechRise STEM — Ambasade y'Amerika, Kigali",
      },
      {
        src: "/images/Gallery/norrsken-late-night.jpeg",
        alt: "Gukorera ijoro mu Norrsken House Kigali",
        caption: "Gukorera Ijoro — Norrsken House",
      },
    ],
    certifications: [
      { name: "Impamyabumenyi muri Cybersecurity (CC)", issuer: "ISC2", year: 2022 },
      { name: "Icyemezo cya IOC Learning Sprint", issuer: "IOC Young Leaders", year: 2024 },
      { name: "Icyemezo cy'Ubuhanga mu Buyobozi (iLead)", issuer: "Maxwell Leadership Foundation", year: 2024 },
      { name: "Icyemezo cy'imyitozo ngiro mu by'imashini zikora", issuer: "AIMS", year: 2023 },
      { name: "Icyemezo cya Club ya Siyansi", issuer: "New Life Christian High School", year: 2024 },
    ],
    skills: [
      { category: "AI & Prompt Engineering", items: ["Claude CLI", "Gemini CLI", "Codex CLI", "LLM APIs", "RAG", "Inzira z'AI", "Prompt Design"] },
      { category: "Indimi zo Guporogaramu", items: ["TypeScript", "JavaScript", "Python", "HTML", "CSS"] },
      { category: "Inzego & Biblioteki", items: ["React 19", "Next.js", "Node.js", "Express.js", "Tailwind CSS", "Framer Motion"] },
      { category: "Imbuga z'Amakuru & Backend", items: ["PostgreSQL", "Supabase", "SQLite", "Upstash Redis", "Vector Search", "Edge Functions"] },
      { category: "Cloud & DevOps", items: ["Vercel", "Git", "GitHub", "REST APIs", "Vite"] },
      { category: "Robotics & Donanım", items: ["Arduino", "Mikoro-ntumwa", "Utwumvirizo", "Moteri", "C++"] },
      { category: "Indimi Mvugwa", items: ["Ikinyarwanda (Ururimi kavukire)", "Icyongereza (C1)", "Igifaransa (Hagati)"] },
    ],
    nav: {
      about: "Ibyanjye",
      experience: "Inararibonye",
      projects: "Imishinga",
      skills: "Ubumenyi",
      education: "Amashuri",
      gallery: "Igalari",
      contact: "Twandikire",
      hireMe: "Bwira Muraho",
    },
    sections: {
      experience: "Inararibonye mu Kazi",
      experienceTagline: "Kuva mu mashuri yisumbuye kugeza mu laboratwari za robotics — kubaka inkingi inzira imwe na imwe.",
      projects: "Imishinga Y'ingenzi",
      projectsTagline: "Ibicuruzwa by'ukuri bikemura ibibazo by'ukuri — byubatswe mu Rwanda, ku Rwanda no hanze.",
      gallery: "Ibihe n'Inzibutso",
      skills: "Ubumenyi n'Ubuhanga",
      skillsTagline: "Inkingi za full-stack, prompt engineering nk'intwaro ikomeye, n'inararibonye ya robotics.",
      education: "Amashuri n'Impamyabumenyi",
      contact: "Tuvugane",
      about: "Njyewe mwayo",
      academic: "Amashuri Nize",
      certifications: "Impamyabumenyi",
    },
    contact: {
      title: "Tuvugane",
      subtitle: "Ndashaka amahugurwa no gukorera hamwe",
      description: "Naba ushaka amahugurwa yo igice cy'igihe, gukorera hamwe ku mushinga, cyangwa gusa kuganira ku ikoranabuhanga? Naba ufite igitekerezo, amahirwe, cyangwa ushaka gusa kuramukanya — nzishimira gukomezanya nawe.",
      name: "Izina ryawe",
      email: "Imeri yawe",
      phone: "Telefoni",
      address: "Aho uherereye",
      subject: "Icyo uvugaho",
      message: "Ubutumwa",
      send: "Ohereza Ubutumwa",
      sending: "Ubutumwa buracyoherezwa...",
      success: "Ubutumwa bwoherejwe neza!",
      error: "Hagize ikibazo kiba. Ongera ugerageze.",
      namePlaceholder: "Izina ryawe hano",
      emailPlaceholder: "imeri@urubuga.rw",
      messagePlaceholder: "Andika ubutumwa bwawe hano...",
    },
    footer: {
      rights: "Uburenganzira bwose burasigasigwa.",
      visits: "Abasuye Urubuga",
    },
    ui: {
      welcome: "Murakaza neza ku rubuga rwanjye",
      getInTouch: "Tuvugane",
      viewWork: "Reba Imishinga",
      scrollDown: "Manuka Hasi",
      nationality: "Ubwenegihugu",
      born: "Yavutse",
      curiosity: "Amatsiko",
      innovation: "Iguhoraho",
      drivenBy: "Biyobowe n'",
      focusedOn: "Bishingiye ku",
      heroTagline: "Nubaka ibikorwa bya murandasi nifashishije React & TypeScript — nkabita vuba nifashishije Claude CLI, Gemini CLI & Codex CLI.",
      aboutLabel: "// ibyerekeye njye",
      aboutHeadlineMain: "Umunyeshuri. Ubaka.",
      aboutHeadlineAccent: "AI-Native.",
      aboutStat: "5+",
      aboutStatLabel: "Impamyabumenyi & Ibihembo",
      aboutTags: "CS @ Kaminuza y'u Rwanda|ISC2 Certified|Ubushakashatsi bw'Imashini|u Rwanda 🇷🇼|Ubaka na AI ⚡",
      viewLive: "Reba Urubuga",
      viewCode: "Reba Code",
      soloProject: "Wenyine",
      teamProject: "Ikipe",
      builtFor: "Yubatswe kuri:",
      beyondCodeLabel: "// hanze y'amakode",
      beyondCodeHeadline: "Igihe ntubaka",
      beyondCodeCopy: "Ubona nkora joginge ku misozi ya Kigali, ngerageza inzira za CBD hafi ya Convention Centre, cyangwa nreba inyandamutoranyamudiho z'imodoka kuri YouTube — imodoka nshya, ibigereranyo, n'imodoka zasubijwe imiterere. Nizeye ko injeniyeri nziza zisigara zifite ubushake — kuguma mu ngendo bitera ibitekerezo bishya.",
      beyondCodeTags: "🏃 Joginge|🚶 Kugenda Kigali|🚗 Imodoka kuri YouTube|🌆 Gushakashaka Umujyi|☕ Ikiganiro na Kawa|📚 Gusoma",
    }
  },
  fr: {
    title: "Ingénieur Full-Stack & Ingénieur Prompt",
    about: "J'ai grandi au Rwanda et j'ai terminé le lycée avec une spécialisation en Mathématiques, Physique et Informatique à la New Life Christian High School — où j'ai également dirigé le Club Informatique et organisé des sessions de codage pour mes camarades.\n\nJe poursuis actuellement un BSc en Informatique à l'Université du Rwanda, Collège des Sciences et Technologies. En parallèle, j'ai mené des recherches en robotique à l'AIMS, obtenu une certification en Cybersécurité de l'ISC2, et participé aux initiatives technologiques d'A2SV.\n\nMon obsession aujourd'hui est simple : utiliser les outils d'IA agentique — Claude CLI, Gemini CLI et Codex CLI — pour livrer de vrais produits dans le minimum de temps possible. Je crois que l'avantage dans l'ère de l'IA n'est plus la vitesse de codage, mais la qualité du jugement sur ce qu'il faut construire.",
    experience: [
      {
        title: "Chef d'équipe Robotique (Recherche Robot CUE)",
        company: "TechRise Rwanda",
        location: "Kigali, Rwanda",
        period: "Nov 2024 – Fév 2025",
        description: [
          "Direction d'une équipe de recherche étudiant le robot CUE.",
          "Exploration de l'histoire, de la fonctionnalité et de la programmation.",
          "Réalisation de tests à l'aide de défis pré-codés.",
          "Présentation des résultats et des perspectives aux parties prenantes.",
        ],
      },
      {
        title: "Président du club scientifique du département informatique",
        company: "New Life Christian High School",
        location: "Kigali, Rwanda",
        period: "Oct 2023 – Juil 2024",
        description: [
          "Direction d'une équipe dans le développement de projets web simples.",
          "Conception et mise en œuvre de solutions web front-end et back-end de base.",
          "Organisation et animation de sessions de codage pour les étudiants.",
          "Conseils techniques sur les bases du HTML, CSS et JavaScript.",
          "Gestion des délais de projet et garantie de la collaboration d'équipe.",
        ],
      },
      {
        title: "Stagiaire en Robotique et Programmation",
        company: "African Institute for Mathematical Sciences (AIMS)",
        location: "Kigali, Rwanda",
        period: "Mar 2022 – Juil 2023",
        description: [
          "Programmation robotique pratique avec capteurs, moteurs et microcontrôleurs.",
          "Application des compétences en programmation aux défis de la robotique.",
          "Collaboration sur des applications robotiques réelles.",
        ],
      },
      {
        title: "Stagiaire en Fondamentaux de la Cybersécurité",
        company: "ISC2",
        location: "Kigali, Rwanda",
        period: "Août 2022 – Sept 2022",
        description: [
          "Cours Certified in Cybersecurity (CC) terminé.",
          "Connaissances de base en sécurité réseau et analyse des menaces.",
          "Apprentissage de la réponse aux incidents et des meilleures pratiques de sécurité.",
        ],
      },
    ],
    education: [
      {
        degree: "Licence en Informatique",
        institution: "Université du Rwanda, Collège des Sciences et Technologies",
        period: "2024 – Présent",
        website: "https://ur.ac.rw/",
      },
      {
        degree: "Certificat Général Avancé d'Enseignement Secondaire",
        institution: "New Life Christian High School",
        period: "2021 – 2024",
        website: "https://nlca.ac.rw/",
      },
      {
        degree: "Prompt Engineering & IA Agentique",
        institution: "Apprentissage Autonome · Continu",
        period: "2024 – Présent",
        type: "continuous",
        tags: ["Claude API", "Gemini", "Codex", "RAG", "Workflows Agentiques", "Design LLM"],
      },
    ],
    projects: [
      {
        title: "Rwanda Tourist Assistant",
        problem: "Planifier un voyage au Rwanda est complexe — trop d'options, aucun guide personnalisé.",
        description: "Un compagnon de voyage IA alimenté par RAG qui fournit des recommandations instantanées et personnalisées pour plus de 100 destinations rwandaises. Filtrez par type d'expérience (Nature, Culture, Aventure), budget et durée — en français, anglais ou kinyarwanda.",
        target: "Touristes & voyageurs qui explorent le Rwanda",
        image: "/images/rwanda-tour-image.jpg",
        link: "https://rwanda-tour-ai.vercel.app",
        github: "https://github.com/danielstriver/rwanda-tour-ai",
        tags: ["React 19", "TypeScript", "Hugging Face", "Supabase Vector", "Upstash Redis", "Vercel"],
        type: "Solo",
      },
      {
        title: "PowerSync",
        problem: "Saisir un code de 20 chiffres à chaque achat d'électricité — dans le noir, chaque fois.",
        description: "Une plateforme de microgrids intelligents qui active l'électricité instantanément dès que vous payez via mobile money. Aucun code. Aucune attente. Payez depuis votre téléphone, le courant arrive immédiatement — conçu pour chaque Rwandais.",
        target: "Tous les utilisateurs d'électricité au Rwanda",
        image: "/images/project2-image.jpeg",
        link: "https://powersync-rw.vercel.app/",
        github: "https://github.com/danielstriver/powersync",
        tags: ["Next.js", "TypeScript", "IoT", "Mobile Money", "Solar"],
        type: "Team",
      },
      {
        title: "Prochain Projet",
        description: "Quelque chose de nouveau est en construction. La robotique rencontre des problèmes réels — restez connecté.",
        image: "/images/logo.png",
        status: "Prochainement",
      },
    ],
    gallery: [
      {
        src: "/images/Gallery/scratch-competition.jpg",
        alt: "Daniel présentant un projet Scratch en compétition",
        caption: "Compétition de Programmation Scratch",
      },
      {
        src: "/images/Gallery/techrise-stem-us-embassy.jpeg",
        alt: "Daniel lors de la formation TechRise STEM, Centre Américain de l'Ambassade US, Kigali",
        caption: "Formation TechRise STEM — Ambassade US, Kigali",
      },
      {
        src: "/images/Gallery/norrsken-late-night.jpeg",
        alt: "Session de code tardive à Norrsken House Kigali",
        caption: "Session de Code en Soirée — Norrsken House",
      },
    ],
    certifications: [
      { name: "Certifié en Cybersécurité (CC)", issuer: "ISC2", year: 2022 },
      { name: "Certificat d'apprentissage IOC", issuer: "Jeunes leaders du CIO", year: 2024 },
      { name: "Certificat de Leadership iLead", issuer: "Fondation Maxwell Leadership", year: 2024 },
      { name: "Certificat d'apprentissage en robotique", issuer: "AIMS", year: 2023 },
      { name: "Certificat du club scientifique", issuer: "New Life Christian High School", year: 2024 },
    ],
    skills: [
      { category: "IA & Prompt Engineering", items: ["Claude CLI", "Gemini CLI", "Codex CLI", "APIs LLM", "RAG", "Workflows Agentiques", "Prompt Design"] },
      { category: "Langages", items: ["TypeScript", "JavaScript", "Python", "HTML", "CSS"] },
      { category: "Frameworks & Bibliothèques", items: ["React 19", "Next.js", "Node.js", "Express.js", "Tailwind CSS", "Framer Motion"] },
      { category: "Bases de Données & Backend", items: ["PostgreSQL", "Supabase", "SQLite", "Upstash Redis", "Recherche Vectorielle", "Edge Functions"] },
      { category: "Cloud & DevOps", items: ["Vercel", "Git", "GitHub", "REST APIs", "Vite"] },
      { category: "Robotique & Matériel", items: ["Arduino", "Microcontrôleurs", "Capteurs", "Moteurs", "C++"] },
      { category: "Langues Parlées", items: ["Kinyarwanda (Langue maternelle)", "Anglais (C1)", "Français (Intermédiaire)"] },
    ],
    nav: {
      about: "À Propos",
      experience: "Expérience",
      projects: "Projets",
      skills: "Compétences",
      education: "Éducation",
      gallery: "Galerie",
      contact: "Contact",
      hireMe: "Dire Bonjour",
    },
    sections: {
      experience: "Expérience Professionnelle",
      experienceTagline: "Du club informatique du lycée aux laboratoires de robotique — construire les bases, une étape à la fois.",
      projects: "Projets Phares",
      projectsTagline: "Des produits réels pour des problèmes réels — conçus au Rwanda, pour le Rwanda et au-delà.",
      gallery: "Moments & Souvenirs",
      skills: "Compétences & Expertise",
      skillsTagline: "Bases full-stack solides, prompt engineering comme superpouvoir, et une expérience robotique pour rester ancré dans le réel.",
      education: "Éducation & Certifications",
      contact: "Contactez-moi",
      about: "À Propos",
      academic: "Parcours Académique",
      certifications: "Certifications",
    },
    contact: {
      title: "Contactez-moi",
      subtitle: "Ouvert aux stages et collaborations",
      description: "Intéressé par des stages à temps partiel, des projets collaboratifs, ou simplement envie de parler tech ? Que vous ayez une idée de projet, une opportunité à partager, ou juste envie de dire bonjour — j'adorerais vous lire.",
      name: "Votre Nom",
      email: "Adresse Email",
      phone: "Téléphone",
      address: "Adresse",
      subject: "Sujet",
      message: "Message",
      send: "Envoyer le Message",
      sending: "Envoi du message...",
      success: "Message envoyé avec succès !",
      error: "Une erreur est survenue. Veuillez réessayer.",
      namePlaceholder: "Jean Dupont",
      emailPlaceholder: "jean@exemple.fr",
      messagePlaceholder: "Partagez quelques détails sur votre projet, votre rôle ou votre question.",
    },
    footer: {
      rights: "Tous droits réservés.",
      visits: "Visites du Site",
    },
    ui: {
      welcome: "Bienvenue sur mon portfolio",
      getInTouch: "Contactez-moi",
      viewWork: "Voir mes Projets",
      scrollDown: "Défiler vers le bas",
      nationality: "Nationalité",
      born: "Né",
      curiosity: "Curiosité",
      innovation: "Innovation",
      drivenBy: "Animé par",
      focusedOn: "Axé sur",
      heroTagline: "Je développe des applications web performantes avec React & TypeScript — et les livre à la vitesse de l'IA grâce à Claude CLI, Gemini CLI & Codex CLI.",
      aboutLabel: "// à propos de moi",
      aboutHeadlineMain: "Étudiant. Bâtisseur.",
      aboutHeadlineAccent: "AI-Natif.",
      aboutStat: "5+",
      aboutStatLabel: "Certifications & Prix",
      aboutTags: "CS @ Univ. du Rwanda|Certifié ISC2|Recherche en Robotique|Rwanda 🇷🇼|Bâtisseur AI ⚡",
      viewLive: "Démo Live",
      viewCode: "Voir le Code",
      soloProject: "Solo",
      teamProject: "Équipe",
      builtFor: "Pour :",
      beyondCodeLabel: "// au-delà du code",
      beyondCodeHeadline: "Quand je ne construis pas",
      beyondCodeCopy: "Vous me trouverez en train de courir dans les collines de Kigali, de parcourir le quartier premium près du Centre de Conférences, ou plongé dans YouTube à regarder des émissions automobiles — révélations de nouveaux modèles, critiques et restomods. Je crois que les meilleurs ingénieurs restent curieux — et rester en mouvement, c'est garder les idées vivantes.",
      beyondCodeTags: "🏃 Running|🚶 Marche à Kigali|🚗 Car Shows YouTube|🌆 Explorer la Ville|☕ Cafés Talks|📚 Lecture",
    }
  },
  es: {
    title: "Ingeniero Full-Stack & Ingeniero de Prompts",
    about: "Crecí en Ruanda y terminé el bachillerato con especialización en Matemáticas, Física e Informática en la New Life Christian High School — donde también lideré el Club de Informática y organicé sesiones de programación para mis compañeros.\n\nActualmente curso un BSc en Informática en la Universidad de Ruanda, Facultad de Ciencias y Tecnología. En el camino, realicé investigación práctica en robótica en el AIMS, obtuve la certificación en Ciberseguridad de ISC2 y participé en iniciativas tecnológicas de A2SV.\n\nMi obsesión hoy es simple: usar herramientas de IA agentiva — Claude CLI, Gemini CLI y Codex CLI — para lanzar productos reales en el mínimo tiempo posible. Creo que la ventaja en la era de la IA ya no es la velocidad al codificar. Es la calidad del juicio sobre qué construir.",
    experience: [
      {
        title: "Líder del Equipo de Robótica (Investigación Robot CUE)",
        company: "TechRise Rwanda",
        location: "Kigali, Ruanda",
        period: "Nov 2024 – Feb 2025",
        description: [
          "Lideré un equipo de investigación que estudia el robot CUE.",
          "Exploré historia, funcionalidad y programación del robot.",
          "Realicé pruebas utilizando desafíos pre-programados.",
          "Presenté hallazgos y perspectivas a las partes interesadas.",
        ],
      },
      {
        title: "Presidente del Club de Ciencias Informáticas",
        company: "New Life Christian High School",
        location: "Kigali, Ruanda",
        period: "Oct 2023 – Jul 2024",
        description: [
          "Lideré un equipo en el desarrollo de proyectos web sencillos.",
          "Diseñé e implementé soluciones web front-end y back-end básicas.",
          "Organicé y facilité sesiones de programación para estudiantes.",
          "Proporcioné orientación técnica en HTML, CSS y JavaScript.",
          "Gestioné plazos de proyectos y garanticé la colaboración del equipo.",
        ],
      },
      {
        title: "Pasante en Robótica y Programación",
        company: "African Institute for Mathematical Sciences (AIMS)",
        location: "Kigali, Ruanda",
        period: "Mar 2022 – Jul 2023",
        description: [
          "Programación práctica de robots con sensores, motores y microcontroladores.",
          "Apliqué habilidades de programación a desafíos robóticos.",
          "Colaboré en aplicaciones robóticas del mundo real.",
        ],
      },
      {
        title: "Pasante en Fundamentos de Ciberseguridad",
        company: "ISC2",
        location: "Kigali, Ruanda",
        period: "Ago 2022 – Sep 2022",
        description: [
          "Completé el curso Certified in Cybersecurity (CC).",
          "Adquirí conocimientos básicos en seguridad de redes y análisis de amenazas.",
          "Aprendí respuesta a incidentes y mejores prácticas de seguridad.",
        ],
      },
    ],
    education: [
      {
        degree: "Licenciatura en Informática",
        institution: "Universidad de Ruanda, Facultad de Ciencias y Tecnología",
        period: "2024 – Presente",
        website: "https://ur.ac.rw/",
      },
      {
        degree: "Certificado General Avanzado de Educación Secundaria",
        institution: "New Life Christian High School",
        period: "2021 – 2024",
        website: "https://nlca.ac.rw/",
      },
      {
        degree: "Ingeniería de Prompts & IA Agentiva",
        institution: "Aprendizaje Autónomo · Continuo",
        period: "2024 – Presente",
        type: "continuous",
        tags: ["Claude API", "Gemini", "Codex", "RAG", "Flujos Agentivos", "Diseño LLM"],
      },
    ],
    projects: [
      {
        title: "Rwanda Tourist Assistant",
        problem: "Planificar un viaje a Ruanda es abrumador — demasiadas opciones, cero orientación personalizada.",
        description: "Un compañero de viaje IA basado en RAG que ofrece recomendaciones instantáneas y personalizadas para más de 100 destinos ruandeses. Filtra por tipo de experiencia (Naturaleza, Cultura, Aventura), presupuesto y duración del viaje — en inglés, francés o kinyarwanda.",
        target: "Turistas y viajeros que exploran Ruanda",
        image: "/images/rwanda-tour-image.jpg",
        link: "https://rwanda-tour-ai.vercel.app",
        github: "https://github.com/danielstriver/rwanda-tour-ai",
        tags: ["React 19", "TypeScript", "Hugging Face", "Supabase Vector", "Upstash Redis", "Vercel"],
        type: "Solo",
      },
      {
        title: "PowerSync",
        problem: "Ingresar un código de 20 dígitos cada vez que compras electricidad — a oscuras, siempre.",
        description: "Una plataforma de microrred inteligente que activa la electricidad al instante cuando pagas por móvil. Sin código. Sin espera. Compra desde tu teléfono, el suministro llega de inmediato — diseñado para cada hogar ruandés.",
        target: "Todos los usuarios de electricidad en Ruanda",
        image: "/images/project2-image.jpeg",
        link: "https://powersync-rw.vercel.app/",
        github: "https://github.com/danielstriver/powersync",
        tags: ["Next.js", "TypeScript", "IoT", "Mobile Money", "Solar"],
        type: "Equipo",
      },
      {
        title: "Próximo Proyecto",
        description: "Algo nuevo está siendo construido. La robótica se encuentra con la resolución de problemas reales — pendiente.",
        image: "/images/logo.png",
        status: "Próximamente",
      },
    ],
    gallery: [
      {
        src: "/images/Gallery/scratch-competition.jpg",
        alt: "Daniel presentando en la competición de programación Scratch",
        caption: "Competición de Programación Scratch",
      },
      {
        src: "/images/Gallery/techrise-stem-us-embassy.jpeg",
        alt: "Daniel en la formación TechRise STEM, Centro Americano de la Embajada de EE.UU., Kigali",
        caption: "Formación TechRise STEM — Embajada de EE.UU., Kigali",
      },
      {
        src: "/images/Gallery/norrsken-late-night.jpeg",
        alt: "Sesión de programación nocturna en Norrsken House Kigali",
        caption: "Sesión de Código Nocturna — Norrsken House",
      },
    ],
    certifications: [
      { name: "Certificado en Ciberseguridad (CC)", issuer: "ISC2", year: 2022 },
      { name: "Certificado IOC Learning Sprint", issuer: "IOC Young Leaders", year: 2024 },
      { name: "Certificado de Liderazgo iLead", issuer: "Maxwell Leadership Foundation", year: 2024 },
      { name: "Certificado de Aprendizaje en Robótica", issuer: "AIMS", year: 2023 },
      { name: "Certificado del Club de Ciencias", issuer: "New Life Christian High School", year: 2024 },
    ],
    skills: [
      { category: "IA & Ingeniería de Prompts", items: ["Claude CLI", "Gemini CLI", "Codex CLI", "LLM APIs", "RAG", "Flujos Agentivos", "Diseño de Prompts"] },
      { category: "Lenguajes", items: ["TypeScript", "JavaScript", "Python", "HTML", "CSS"] },
      { category: "Frameworks & Bibliotecas", items: ["React 19", "Next.js", "Node.js", "Express.js", "Tailwind CSS", "Framer Motion"] },
      { category: "Bases de Datos & Backend", items: ["PostgreSQL", "Supabase", "SQLite", "Upstash Redis", "Búsqueda Vectorial", "Edge Functions"] },
      { category: "Cloud & DevOps", items: ["Vercel", "Git", "GitHub", "REST APIs", "Vite"] },
      { category: "Robótica & Hardware", items: ["Arduino", "Microcontroladores", "Sensores", "Motores", "C++"] },
      { category: "Idiomas Hablados", items: ["Kinyarwanda (Nativo)", "Inglés (C1)", "Francés (Intermedio)"] },
    ],
    nav: {
      about: "Sobre Mí",
      experience: "Experiencia",
      projects: "Proyectos",
      skills: "Habilidades",
      education: "Educación",
      gallery: "Galería",
      contact: "Contacto",
      hireMe: "Saludar",
    },
    sections: {
      experience: "Experiencia Profesional",
      experienceTagline: "Del club de informática del instituto a los laboratorios de robótica — construyendo la base paso a paso.",
      projects: "Proyectos Destacados",
      projectsTagline: "Productos reales resolviendo problemas reales — desarrollados desde Ruanda, para Ruanda y más allá.",
      gallery: "Momentos y Recuerdos",
      skills: "Habilidades y Experiencia",
      skillsTagline: "Bases full-stack, ingeniería de prompts como superpoder y experiencia en robótica para mantener los pies en la tierra.",
      education: "Educación y Certificaciones",
      contact: "Contactar",
      about: "Sobre Mí",
      academic: "Trayectoria Académica",
      certifications: "Certificaciones",
    },
    contact: {
      title: "Contactar",
      subtitle: "Abierto a prácticas y colaboraciones",
      description: "¿Interesado en prácticas a tiempo parcial, proyectos colaborativos, o simplemente quieres hablar de tecnología? Ya sea que tengas una idea de proyecto, una oportunidad o solo quieras saludar — me encantaría saber de ti.",
      name: "Tu Nombre",
      email: "Correo Electrónico",
      phone: "Teléfono",
      address: "Dirección",
      subject: "Asunto",
      message: "Mensaje",
      send: "Enviar Mensaje",
      sending: "Enviando mensaje...",
      success: "¡Mensaje enviado con éxito!",
      error: "Algo salió mal. Por favor intenta de nuevo.",
      namePlaceholder: "Juan García",
      emailPlaceholder: "juan@ejemplo.com",
      messagePlaceholder: "Comparte detalles sobre tu proyecto, rol o pregunta.",
    },
    footer: {
      rights: "Todos los derechos reservados.",
      visits: "Visitas al Sitio",
    },
    ui: {
      welcome: "Bienvenido a mi portafolio",
      getInTouch: "Contactar",
      viewWork: "Ver Proyectos",
      scrollDown: "Desplazar Abajo",
      nationality: "Nacionalidad",
      born: "Nacido",
      curiosity: "Curiosidad",
      innovation: "Innovación",
      drivenBy: "Impulsado por",
      focusedOn: "Enfocado en",
      heroTagline: "Desarrollo aplicaciones web de nivel productivo con React & TypeScript — enviando a velocidad IA con Claude CLI, Gemini CLI & Codex CLI.",
      aboutLabel: "// sobre mí",
      aboutHeadlineMain: "Estudiante. Constructor.",
      aboutHeadlineAccent: "IA-Nativo.",
      aboutStat: "5+",
      aboutStatLabel: "Certificaciones y Premios",
      aboutTags: "CS @ Univ. de Ruanda|Certificado ISC2|Investigación en Robótica|Ruanda 🇷🇼|Constructor IA ⚡",
      viewLive: "Demo en Vivo",
      viewCode: "Ver Código",
      soloProject: "Solo",
      teamProject: "Equipo",
      builtFor: "Para:",
      beyondCodeLabel: "// más allá del código",
      beyondCodeHeadline: "Cuando no estoy construyendo",
      beyondCodeCopy: "Me encontrarás corriendo por las colinas de Kigali, recorriendo el distrito premium cerca del Centro de Convenciones, o inmerso en YouTube viendo programas de autos — nuevos modelos, reseñas y restomods. Creo que los mejores ingenieros se mantienen curiosos — y mantenerse en movimiento hace fluir las ideas.",
      beyondCodeTags: "🏃 Correr|🚶 Caminar Kigali|🚗 Car Shows YouTube|🌆 Explorar la Ciudad|☕ Cafés|📚 Lectura",
    },
  },
  de: {
    title: "Full-Stack-Ingenieur & Prompt-Ingenieur",
    about: "Ich wuchs in Ruanda auf und schloss die Oberschule mit Schwerpunkten in Mathematik, Physik und Informatik an der New Life Christian High School ab – wo ich auch den Informatik-Club leitete und Programmierkurse für Mitschüler organisierte.\n\nAktuell studiere ich BSc Informatik an der University of Rwanda, College of Science and Technology. Dabei betrieb ich praktische Robotikforschung am AIMS, erwarb eine Cybersecurity-Zertifizierung von ISC2 und nahm an Tech-Initiativen bei A2SV teil.\n\nMeine heutige Obsession ist einfach: agentische KI-Tools – Claude CLI, Gemini CLI und Codex CLI – nutzen, um echte Produkte in minimaler Zeit zu liefern. Ich glaube, der Vorteil im KI-Zeitalter liegt nicht mehr in der Codiergeschwindigkeit, sondern im Urteilsvermögen darüber, was gebaut werden sollte.",
    experience: [
      {
        title: "Robotik-Teamleiter (CUE-Roboterforschung)",
        company: "TechRise Rwanda",
        location: "Kigali, Ruanda",
        period: "Nov 2024 – Feb 2025",
        description: [
          "Leitete ein Forschungsteam zur Untersuchung des CUE-Roboters.",
          "Erforschte Geschichte, Funktionalität und Programmierung.",
          "Führte Tests mit vorprogrammierten Herausforderungen durch.",
          "Präsentierte Erkenntnisse und Ergebnisse den Stakeholdern.",
        ],
      },
      {
        title: "Präsident des Informatik-Clubs",
        company: "New Life Christian High School",
        location: "Kigali, Ruanda",
        period: "Okt 2023 – Jul 2024",
        description: [
          "Leitete ein Team bei der Entwicklung einfacher Webprojekte.",
          "Entwarf und implementierte grundlegende Front-End- und Back-End-Weblösungen.",
          "Organisierte und leitete Programmierkurse für Mitschüler.",
          "Gab technische Anleitung zu HTML-, CSS- und JavaScript-Grundlagen.",
          "Verwaltete Projektzeitpläne und sicherte die Teamzusammenarbeit.",
        ],
      },
      {
        title: "Praktikant für Robotik und Programmierung",
        company: "African Institute for Mathematical Sciences (AIMS)",
        location: "Kigali, Ruanda",
        period: "Mär 2022 – Jul 2023",
        description: [
          "Praktische Robotikprogrammierung mit Sensoren, Motoren und Mikrocontrollern.",
          "Programmierkenntnisse auf Robotikherausforderungen angewendet.",
          "An praxisnahen Robotikanwendungen mitgearbeitet.",
        ],
      },
      {
        title: "Praktikant für Cybersicherheitsgrundlagen",
        company: "ISC2",
        location: "Kigali, Ruanda",
        period: "Aug 2022 – Sep 2022",
        description: [
          "Certified in Cybersecurity (CC)-Kurs abgeschlossen.",
          "Grundlagenwissen in Netzwerksicherheit und Bedrohungsanalyse erworben.",
          "Vorfallreaktion und Sicherheits-Best-Practices erlernt.",
        ],
      },
    ],
    education: [
      {
        degree: "BSc Informatik",
        institution: "University of Rwanda, College of Science and Technology",
        period: "2024 – Heute",
        website: "https://ur.ac.rw/",
      },
      {
        degree: "Allgemeines Hochschulzeugnis",
        institution: "New Life Christian High School",
        period: "2021 – 2024",
        website: "https://nlca.ac.rw/",
      },
      {
        degree: "Prompt-Engineering & Agentische KI",
        institution: "Selbstgesteuertes · Kontinuierliches Lernen",
        period: "2024 – Heute",
        type: "continuous",
        tags: ["Claude API", "Gemini", "Codex", "RAG", "Agentische Workflows", "LLM-Design"],
      },
    ],
    projects: [
      {
        title: "Rwanda Tourist Assistant",
        problem: "Eine Ruanda-Reise zu planen ist überwältigend — zu viele Optionen, keine persönliche Beratung.",
        description: "Ein KI-Reisebegleiter auf Basis von RAG mit sofortigen, personalisierten Empfehlungen für über 100 ruandische Reiseziele. Filtern nach Erlebnistyp (Natur, Kultur, Abenteuer), Budget und Reisedauer — auf Englisch, Französisch oder Kinyarwanda.",
        target: "Touristen & Reisende, die Ruanda erkunden",
        image: "/images/rwanda-tour-image.jpg",
        link: "https://rwanda-tour-ai.vercel.app",
        github: "https://github.com/danielstriver/rwanda-tour-ai",
        tags: ["React 19", "TypeScript", "Hugging Face", "Supabase Vector", "Upstash Redis", "Vercel"],
        type: "Solo",
      },
      {
        title: "PowerSync",
        problem: "Bei jedem Stromkauf einen 20-stelligen Code eingeben — im Dunkeln, jedes Mal.",
        description: "Eine intelligente Mikronetz-Plattform, die Strom sofort aktiviert, sobald die Zahlung per Mobile Money erfolgt. Kein Code. Kein Warten. Vom Handy kaufen, Strom fließt sofort — entwickelt für jeden ruandischen Haushalt.",
        target: "Alle Stromnutzer in Ruanda",
        image: "/images/project2-image.jpeg",
        link: "https://powersync-rw.vercel.app/",
        github: "https://github.com/danielstriver/powersync",
        tags: ["Next.js", "TypeScript", "IoT", "Mobile Money", "Solar"],
        type: "Team",
      },
      {
        title: "Nächstes Projekt",
        description: "Etwas Neues entsteht gerade. Robotik trifft auf reale Problemlösung — gespannt bleiben.",
        image: "/images/logo.png",
        status: "Demnächst",
      },
    ],
    gallery: [
      {
        src: "/images/Gallery/scratch-competition.jpg",
        alt: "Daniel präsentiert beim Scratch-Programmierwettbewerb",
        caption: "Scratch-Programmierwettbewerb",
      },
      {
        src: "/images/Gallery/techrise-stem-us-embassy.jpeg",
        alt: "Daniel bei der TechRise STEM-Schulung, US-Botschaft American Center, Kigali",
        caption: "TechRise STEM-Schulung — US-Botschaft, Kigali",
      },
      {
        src: "/images/Gallery/norrsken-late-night.jpeg",
        alt: "Nächtliche Programmiersitzung in Norrsken House Kigali",
        caption: "Nächtliche Coding-Session — Norrsken House",
      },
    ],
    certifications: [
      { name: "Zertifiziert in Cybersicherheit (CC)", issuer: "ISC2", year: 2022 },
      { name: "IOC Learning Sprint Zertifikat", issuer: "IOC Young Leaders", year: 2024 },
      { name: "iLead Führungszertifikat", issuer: "Maxwell Leadership Foundation", year: 2024 },
      { name: "Robotik-Lernerfahrung Zertifikat", issuer: "AIMS", year: 2023 },
      { name: "Wissenschaftsclub-Zertifikat", issuer: "New Life Christian High School", year: 2024 },
    ],
    skills: [
      { category: "KI & Prompt-Engineering", items: ["Claude CLI", "Gemini CLI", "Codex CLI", "LLM APIs", "RAG", "Agentische Workflows", "Prompt-Design"] },
      { category: "Programmiersprachen", items: ["TypeScript", "JavaScript", "Python", "HTML", "CSS"] },
      { category: "Frameworks & Bibliotheken", items: ["React 19", "Next.js", "Node.js", "Express.js", "Tailwind CSS", "Framer Motion"] },
      { category: "Datenbanken & Backend", items: ["PostgreSQL", "Supabase", "SQLite", "Upstash Redis", "Vektorsuche", "Edge Functions"] },
      { category: "Cloud & DevOps", items: ["Vercel", "Git", "GitHub", "REST APIs", "Vite"] },
      { category: "Robotik & Hardware", items: ["Arduino", "Mikrocontroller", "Sensoren", "Motoren", "C++"] },
      { category: "Gesprochene Sprachen", items: ["Kinyarwanda (Muttersprache)", "Englisch (C1)", "Französisch (Mittelstufe)"] },
    ],
    nav: {
      about: "Über Mich",
      experience: "Erfahrung",
      projects: "Projekte",
      skills: "Fähigkeiten",
      education: "Bildung",
      gallery: "Galerie",
      contact: "Kontakt",
      hireMe: "Hallo Sagen",
    },
    sections: {
      experience: "Berufserfahrung",
      experienceTagline: "Vom Informatik-Club in der Schule bis zu Robotiklabors — Schritt für Schritt das Fundament aufbauen.",
      projects: "Ausgewählte Projekte",
      projectsTagline: "Echte Produkte für echte Probleme — entwickelt in Ruanda, für Ruanda und darüber hinaus.",
      gallery: "Momente & Erinnerungen",
      skills: "Fähigkeiten & Expertise",
      skillsTagline: "Solide Full-Stack-Grundlagen, Prompt-Engineering als Superkraft und Robotik-Erfahrung für den Praxisbezug.",
      education: "Bildung & Zertifizierungen",
      contact: "Kontakt aufnehmen",
      about: "Über Mich",
      academic: "Akademischer Werdegang",
      certifications: "Zertifizierungen",
    },
    contact: {
      title: "Kontakt aufnehmen",
      subtitle: "Offen für Praktika & Zusammenarbeit",
      description: "Interesse an Teilzeitpraktika, gemeinsamen Projekten oder einfach über Technik reden? Ob Projektidee, Möglichkeit oder einfach Hallo sagen — ich freue mich von Ihnen zu hören.",
      name: "Ihr Name",
      email: "E-Mail-Adresse",
      phone: "Telefon",
      address: "Adresse",
      subject: "Betreff",
      message: "Nachricht",
      send: "Nachricht senden",
      sending: "Nachricht wird gesendet...",
      success: "Nachricht erfolgreich gesendet!",
      error: "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
      namePlaceholder: "Max Mustermann",
      emailPlaceholder: "max@beispiel.de",
      messagePlaceholder: "Teilen Sie Details zu Ihrem Projekt, Ihrer Rolle oder Ihrer Frage.",
    },
    footer: {
      rights: "Alle Rechte vorbehalten.",
      visits: "Website-Besuche",
    },
    ui: {
      welcome: "Willkommen in meinem Portfolio",
      getInTouch: "Kontakt aufnehmen",
      viewWork: "Projekte ansehen",
      scrollDown: "Nach unten scrollen",
      nationality: "Nationalität",
      born: "Geboren",
      curiosity: "Neugier",
      innovation: "Innovation",
      drivenBy: "Angetrieben von",
      focusedOn: "Fokussiert auf",
      heroTagline: "Ich entwickle produktionsreife Web-Apps mit React & TypeScript — und liefere sie in KI-Geschwindigkeit mit Claude CLI, Gemini CLI & Codex CLI.",
      aboutLabel: "// über mich",
      aboutHeadlineMain: "Student. Entwickler.",
      aboutHeadlineAccent: "KI-Nativ.",
      aboutStat: "5+",
      aboutStatLabel: "Zertifizierungen & Auszeichnungen",
      aboutTags: "Informatik @ Univ. Ruanda|ISC2 Zertifiziert|Robotikforschung|Ruanda 🇷🇼|KI-Entwickler ⚡",
      viewLive: "Live-Demo",
      viewCode: "Code ansehen",
      soloProject: "Solo",
      teamProject: "Team",
      builtFor: "Für:",
      beyondCodeLabel: "// jenseits des Codes",
      beyondCodeHeadline: "Wenn ich nicht entwickle",
      beyondCodeCopy: "Ich laufe durch Kigalis Hügel, erforsche das Premium-Viertel nahe dem Convention Centre oder vertiefe mich auf YouTube in Auto-Shows — neue Modellpräsentationen, Reviews und Restomods. Ich glaube, die besten Ingenieure bleiben neugierig — und in Bewegung zu bleiben hält die Ideen frisch.",
      beyondCodeTags: "🏃 Laufen|🚶 Kigali Erkunden|🚗 YouTube Auto-Shows|🌆 Stadtentdeckung|☕ Kaffeegespräche|📚 Lesen",
    },
  },
  pt: {
    title: "Engenheiro Full-Stack & Engenheiro de Prompts",
    about: "Cresci em Ruanda e conclui o ensino médio com especialização em Matemática, Física e Informática na New Life Christian High School — onde também liderei o Clube de Informática e organizei sessões de programação para colegas.\n\nAtualmente curso BSc em Ciências da Computação na Universidade do Ruanda, Faculdade de Ciências e Tecnologia. Ao longo do caminho, realizei pesquisa prática em robótica no AIMS, obtive a certificação em Cibersegurança da ISC2 e participei de iniciativas tecnológicas da A2SV.\n\nMinha obsessão hoje é simples: utilizar ferramentas de IA agentiva — Claude CLI, Gemini CLI e Codex CLI — para lançar produtos reais no menor tempo possível. Acredito que a vantagem na era da IA não é mais a velocidade de codificação. É a qualidade do julgamento sobre o que construir.",
    experience: [
      {
        title: "Líder da Equipe de Robótica (Pesquisa Robot CUE)",
        company: "TechRise Rwanda",
        location: "Kigali, Ruanda",
        period: "Nov 2024 – Fev 2025",
        description: [
          "Lideriei uma equipe de pesquisa estudando o robot CUE.",
          "Explorei história, funcionalidade e programação.",
          "Realizei testes usando desafios pré-programados.",
          "Apresentei descobertas e perspectivas às partes interessadas.",
        ],
      },
      {
        title: "Presidente do Clube de Ciências da Computação",
        company: "New Life Christian High School",
        location: "Kigali, Ruanda",
        period: "Out 2023 – Jul 2024",
        description: [
          "Liderei uma equipe no desenvolvimento de projetos web simples.",
          "Projetei e implementei soluções web front-end e back-end básicas.",
          "Organizei e facilitei sessões de programação para estudantes.",
          "Forneci orientação técnica em HTML, CSS e JavaScript.",
          "Gerenciei cronogramas de projetos garantindo colaboração em equipe.",
        ],
      },
      {
        title: "Estagiário em Robótica e Programação",
        company: "African Institute for Mathematical Sciences (AIMS)",
        location: "Kigali, Ruanda",
        period: "Mar 2022 – Jul 2023",
        description: [
          "Programação prática de robótica com sensores, motores e microcontroladores.",
          "Apliquei habilidades de programação em desafios de robótica.",
          "Colaborei em aplicações robóticas do mundo real.",
        ],
      },
      {
        title: "Estagiário em Fundamentos de Cibersegurança",
        company: "ISC2",
        location: "Kigali, Ruanda",
        period: "Ago 2022 – Set 2022",
        description: [
          "Conclui o curso Certified in Cybersecurity (CC).",
          "Adquiri conhecimentos básicos em segurança de redes e análise de ameaças.",
          "Aprendi resposta a incidentes e melhores práticas de segurança.",
        ],
      },
    ],
    education: [
      {
        degree: "Licenciatura em Ciências da Computação",
        institution: "Universidade do Ruanda, Faculdade de Ciências e Tecnologia",
        period: "2024 – Presente",
        website: "https://ur.ac.rw/",
      },
      {
        degree: "Certificado Geral Avançado do Ensino Médio",
        institution: "New Life Christian High School",
        period: "2021 – 2024",
        website: "https://nlca.ac.rw/",
      },
      {
        degree: "Engenharia de Prompts & IA Agentiva",
        institution: "Aprendizado Autodirigido · Contínuo",
        period: "2024 – Presente",
        type: "continuous",
        tags: ["Claude API", "Gemini", "Codex", "RAG", "Fluxos Agentivos", "Design de LLM"],
      },
    ],
    projects: [
      {
        title: "Rwanda Tourist Assistant",
        problem: "Planejar uma viagem a Ruanda é avassalador — muitas opções, nenhuma orientação personalizada.",
        description: "Um assistente de viagem IA baseado em RAG que oferece recomendações instantâneas e personalizadas para mais de 100 destinos ruandeses. Filtre por tipo de experiência (Natureza, Cultura, Aventura), orçamento e duração da viagem — em inglês, francês ou kinyarwanda.",
        target: "Turistas e viajantes explorando Ruanda",
        image: "/images/rwanda-tour-image.jpg",
        link: "https://rwanda-tour-ai.vercel.app",
        github: "https://github.com/danielstriver/rwanda-tour-ai",
        tags: ["React 19", "TypeScript", "Hugging Face", "Supabase Vector", "Upstash Redis", "Vercel"],
        type: "Solo",
      },
      {
        title: "PowerSync",
        problem: "Digitar um código de 20 dígitos toda vez que compra eletricidade — no escuro, sempre.",
        description: "Uma plataforma de microrrede inteligente que ativa eletricidade instantaneamente ao pagar via dinheiro móvel. Sem código. Sem espera. Compre pelo celular, energia flui imediatamente — construído para cada domicílio ruandês.",
        target: "Todos os usuários de eletricidade em Ruanda",
        image: "/images/project2-image.jpeg",
        link: "https://powersync-rw.vercel.app/",
        github: "https://github.com/danielstriver/powersync",
        tags: ["Next.js", "TypeScript", "IoT", "Mobile Money", "Solar"],
        type: "Equipe",
      },
      {
        title: "Próximo Projeto",
        description: "Algo novo está sendo construído. Robótica encontra resolução de problemas reais — fique atento.",
        image: "/images/logo.png",
        status: "Em Breve",
      },
    ],
    gallery: [
      {
        src: "/images/Gallery/scratch-competition.jpg",
        alt: "Daniel apresentando na competição de programação Scratch",
        caption: "Competição de Programação Scratch",
      },
      {
        src: "/images/Gallery/techrise-stem-us-embassy.jpeg",
        alt: "Daniel no treinamento TechRise STEM, Centro Americano da Embaixada dos EUA, Kigali",
        caption: "Treinamento TechRise STEM — Embaixada dos EUA, Kigali",
      },
      {
        src: "/images/Gallery/norrsken-late-night.jpeg",
        alt: "Sessão de programação noturna no Norrsken House Kigali",
        caption: "Sessão de Código Noturna — Norrsken House",
      },
    ],
    certifications: [
      { name: "Certificado em Cibersegurança (CC)", issuer: "ISC2", year: 2022 },
      { name: "Certificado IOC Learning Sprint", issuer: "IOC Young Leaders", year: 2024 },
      { name: "Certificado de Liderança iLead", issuer: "Maxwell Leadership Foundation", year: 2024 },
      { name: "Certificado de Aprendizagem em Robótica", issuer: "AIMS", year: 2023 },
      { name: "Certificado do Clube de Ciências", issuer: "New Life Christian High School", year: 2024 },
    ],
    skills: [
      { category: "IA & Engenharia de Prompts", items: ["Claude CLI", "Gemini CLI", "Codex CLI", "LLM APIs", "RAG", "Fluxos Agentivos", "Design de Prompts"] },
      { category: "Linguagens", items: ["TypeScript", "JavaScript", "Python", "HTML", "CSS"] },
      { category: "Frameworks & Bibliotecas", items: ["React 19", "Next.js", "Node.js", "Express.js", "Tailwind CSS", "Framer Motion"] },
      { category: "Bancos de Dados & Backend", items: ["PostgreSQL", "Supabase", "SQLite", "Upstash Redis", "Busca Vetorial", "Edge Functions"] },
      { category: "Cloud & DevOps", items: ["Vercel", "Git", "GitHub", "REST APIs", "Vite"] },
      { category: "Robótica & Hardware", items: ["Arduino", "Microcontroladores", "Sensores", "Motores", "C++"] },
      { category: "Idiomas Falados", items: ["Kinyarwanda (Nativo)", "Inglês (C1)", "Francês (Intermediário)"] },
    ],
    nav: {
      about: "Sobre Mim",
      experience: "Experiência",
      projects: "Projetos",
      skills: "Habilidades",
      education: "Educação",
      gallery: "Galeria",
      contact: "Contato",
      hireMe: "Dizer Olá",
    },
    sections: {
      experience: "Experiência Profissional",
      experienceTagline: "Do clube de informática do colégio aos laboratórios de robótica — construindo a base um passo de cada vez.",
      projects: "Projetos em Destaque",
      projectsTagline: "Produtos reais resolvendo problemas reais — desenvolvidos em Ruanda, para Ruanda e além.",
      gallery: "Momentos e Memórias",
      skills: "Habilidades e Expertise",
      skillsTagline: "Bases full-stack sólidas, engenharia de prompts como superpoder e experiência em robótica para manter os pés no chão.",
      education: "Educação e Certificações",
      contact: "Entre em Contato",
      about: "Sobre Mim",
      academic: "Trajetória Acadêmica",
      certifications: "Certificações",
    },
    contact: {
      title: "Entre em Contato",
      subtitle: "Aberto a estágios e colaborações",
      description: "Interessado em estágios de meio período, projetos colaborativos ou apenas quer falar sobre tecnologia? Seja uma ideia de projeto, uma oportunidade ou apenas um olá — adoraria ouvir de você.",
      name: "Seu Nome",
      email: "Endereço de Email",
      phone: "Telefone",
      address: "Endereço",
      subject: "Assunto",
      message: "Mensagem",
      send: "Enviar Mensagem",
      sending: "Enviando mensagem...",
      success: "Mensagem enviada com sucesso!",
      error: "Algo deu errado. Por favor tente novamente.",
      namePlaceholder: "João Silva",
      emailPlaceholder: "joao@exemplo.com",
      messagePlaceholder: "Compartilhe detalhes sobre seu projeto, função ou pergunta.",
    },
    footer: {
      rights: "Todos os direitos reservados.",
      visits: "Visitas ao Site",
    },
    ui: {
      welcome: "Bem-vindo ao meu portfólio",
      getInTouch: "Entre em Contato",
      viewWork: "Ver Projetos",
      scrollDown: "Rolar para Baixo",
      nationality: "Nacionalidade",
      born: "Nascido",
      curiosity: "Curiosidade",
      innovation: "Inovação",
      drivenBy: "Movido por",
      focusedOn: "Focado em",
      heroTagline: "Desenvolvo aplicações web de nível produção com React & TypeScript — entregando na velocidade da IA com Claude CLI, Gemini CLI & Codex CLI.",
      aboutLabel: "// sobre mim",
      aboutHeadlineMain: "Estudante. Construtor.",
      aboutHeadlineAccent: "IA-Nativo.",
      aboutStat: "5+",
      aboutStatLabel: "Certificações & Prêmios",
      aboutTags: "CS @ Univ. do Ruanda|Certificado ISC2|Pesquisa em Robótica|Ruanda 🇷🇼|Construtor IA ⚡",
      viewLive: "Demo ao Vivo",
      viewCode: "Ver Código",
      soloProject: "Solo",
      teamProject: "Equipe",
      builtFor: "Para:",
      beyondCodeLabel: "// além do código",
      beyondCodeHeadline: "Quando não estou construindo",
      beyondCodeCopy: "Você me encontrará correndo pelas colinas de Kigali, caminhando pelo distrito premium perto do Centro de Convenções, ou imerso no YouTube assistindo programas de carros — lançamentos de novos modelos, avaliações e restomods. Acredito que os melhores engenheiros permanecem curiosos — e estar em movimento mantém as ideias fluindo.",
      beyondCodeTags: "🏃 Corrida|🚶 Caminhar Kigali|🚗 Car Shows YouTube|🌆 Explorar a Cidade|☕ Papos de Café|📚 Leitura",
    },
  },
};
